/*
 * This file is generated by jOOQ.
*/
package schemas.public_.tables.records;


import java.sql.Timestamp;

import javax.annotation.Generated;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record10;
import org.jooq.Row10;
import org.jooq.impl.UpdatableRecordImpl;

import schemas.public_.tables.AcademicQualification;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AcademicQualificationRecord extends UpdatableRecordImpl<AcademicQualificationRecord> implements Record10<Long, String, String, Timestamp, String, String, String, String, Timestamp, String> {

    private static final long serialVersionUID = 1688749239;

    /**
     * Setter for <code>public.academic_qualification.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.academic_qualification.id</code>.
     */
    @NotNull
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.academic_qualification.country</code>.
     */
    public void setCountry(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.academic_qualification.country</code>.
     */
    @Size(max = 255)
    public String getCountry() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.academic_qualification.date_of_award</code>.
     */
    public void setDateOfAward(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.academic_qualification.date_of_award</code>.
     */
    @Size(max = 255)
    public String getDateOfAward() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.academic_qualification.end_date</code>.
     */
    public void setEndDate(Timestamp value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.academic_qualification.end_date</code>.
     */
    public Timestamp getEndDate() {
        return (Timestamp) get(3);
    }

    /**
     * Setter for <code>public.academic_qualification.institution_name</code>.
     */
    public void setInstitutionName(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.academic_qualification.institution_name</code>.
     */
    @Size(max = 255)
    public String getInstitutionName() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.academic_qualification.other_achievement</code>.
     */
    public void setOtherAchievement(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.academic_qualification.other_achievement</code>.
     */
    @Size(max = 255)
    public String getOtherAchievement() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.academic_qualification.title_of_qualification</code>.
     */
    public void setTitleOfQualification(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.academic_qualification.title_of_qualification</code>.
     */
    @Size(max = 255)
    public String getTitleOfQualification() {
        return (String) get(6);
    }

    /**
     * Setter for <code>public.academic_qualification.result</code>.
     */
    public void setResult(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.academic_qualification.result</code>.
     */
    @Size(max = 255)
    public String getResult() {
        return (String) get(7);
    }

    /**
     * Setter for <code>public.academic_qualification.start_date</code>.
     */
    public void setStartDate(Timestamp value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.academic_qualification.start_date</code>.
     */
    public Timestamp getStartDate() {
        return (Timestamp) get(8);
    }

    /**
     * Setter for <code>public.academic_qualification.subject</code>.
     */
    public void setSubject(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.academic_qualification.subject</code>.
     */
    @Size(max = 255)
    public String getSubject() {
        return (String) get(9);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record10 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row10<Long, String, String, Timestamp, String, String, String, String, Timestamp, String> fieldsRow() {
        return (Row10) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row10<Long, String, String, Timestamp, String, String, String, String, Timestamp, String> valuesRow() {
        return (Row10) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return AcademicQualification.ACADEMIC_QUALIFICATION.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return AcademicQualification.ACADEMIC_QUALIFICATION.COUNTRY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return AcademicQualification.ACADEMIC_QUALIFICATION.DATE_OF_AWARD;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field4() {
        return AcademicQualification.ACADEMIC_QUALIFICATION.END_DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return AcademicQualification.ACADEMIC_QUALIFICATION.INSTITUTION_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return AcademicQualification.ACADEMIC_QUALIFICATION.OTHER_ACHIEVEMENT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return AcademicQualification.ACADEMIC_QUALIFICATION.TITLE_OF_QUALIFICATION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field8() {
        return AcademicQualification.ACADEMIC_QUALIFICATION.RESULT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field9() {
        return AcademicQualification.ACADEMIC_QUALIFICATION.START_DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field10() {
        return AcademicQualification.ACADEMIC_QUALIFICATION.SUBJECT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getCountry();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getDateOfAward();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value4() {
        return getEndDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getInstitutionName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getOtherAchievement();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getTitleOfQualification();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value8() {
        return getResult();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value9() {
        return getStartDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value10() {
        return getSubject();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AcademicQualificationRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AcademicQualificationRecord value2(String value) {
        setCountry(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AcademicQualificationRecord value3(String value) {
        setDateOfAward(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AcademicQualificationRecord value4(Timestamp value) {
        setEndDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AcademicQualificationRecord value5(String value) {
        setInstitutionName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AcademicQualificationRecord value6(String value) {
        setOtherAchievement(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AcademicQualificationRecord value7(String value) {
        setTitleOfQualification(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AcademicQualificationRecord value8(String value) {
        setResult(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AcademicQualificationRecord value9(Timestamp value) {
        setStartDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AcademicQualificationRecord value10(String value) {
        setSubject(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AcademicQualificationRecord values(Long value1, String value2, String value3, Timestamp value4, String value5, String value6, String value7, String value8, Timestamp value9, String value10) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AcademicQualificationRecord
     */
    public AcademicQualificationRecord() {
        super(AcademicQualification.ACADEMIC_QUALIFICATION);
    }

    /**
     * Create a detached, initialised AcademicQualificationRecord
     */
    public AcademicQualificationRecord(Long id, String country, String dateOfAward, Timestamp endDate, String institutionName, String otherAchievement, String titleOfQualification, String result, Timestamp startDate, String subject) {
        super(AcademicQualification.ACADEMIC_QUALIFICATION);

        set(0, id);
        set(1, country);
        set(2, dateOfAward);
        set(3, endDate);
        set(4, institutionName);
        set(5, otherAchievement);
        set(6, titleOfQualification);
        set(7, result);
        set(8, startDate);
        set(9, subject);
    }
}
