/*
 * This file is generated by jOOQ.
*/
package schemas.public_.tables.records;


import java.sql.Timestamp;

import javax.annotation.Generated;
import javax.validation.constraints.Size;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record13;
import org.jooq.Row13;
import org.jooq.impl.UpdatableRecordImpl;

import schemas.public_.tables.ApplicationDetail;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ApplicationDetailRecord extends UpdatableRecordImpl<ApplicationDetailRecord> implements Record13<String, String, String, String, Timestamp, String, String, Timestamp, String, Long, Long, String, Long> {

    private static final long serialVersionUID = 100490640;

    /**
     * Setter for <code>public.application_detail.admission_officer</code>.
     */
    public void setAdmissionOfficer(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.application_detail.admission_officer</code>.
     */
    @Size(max = 255)
    public String getAdmissionOfficer() {
        return (String) get(0);
    }

    /**
     * Setter for <code>public.application_detail.code</code>.
     */
    public void setCode(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.application_detail.code</code>.
     */
    @Size(max = 255)
    public String getCode() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.application_detail.course_fk</code>.
     */
    public void setCourseFk(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.application_detail.course_fk</code>.
     */
    @Size(max = 255)
    public String getCourseFk() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.application_detail.faculty</code>.
     */
    public void setFaculty(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.application_detail.faculty</code>.
     */
    @Size(max = 255)
    public String getFaculty() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.application_detail.finish_date</code>.
     */
    public void setFinishDate(Timestamp value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.application_detail.finish_date</code>.
     */
    public Timestamp getFinishDate() {
        return (Timestamp) get(4);
    }

    /**
     * Setter for <code>public.application_detail.location_</code>.
     */
    public void setLocation_(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.application_detail.location_</code>.
     */
    @Size(max = 255)
    public String getLocation_() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.application_detail.mode_of_attendance</code>.
     */
    public void setModeOfAttendance(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.application_detail.mode_of_attendance</code>.
     */
    @Size(max = 255)
    public String getModeOfAttendance() {
        return (String) get(6);
    }

    /**
     * Setter for <code>public.application_detail.start_date</code>.
     */
    public void setStartDate(Timestamp value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.application_detail.start_date</code>.
     */
    public Timestamp getStartDate() {
        return (Timestamp) get(7);
    }

    /**
     * Setter for <code>public.application_detail.status</code>.
     */
    public void setStatus(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.application_detail.status</code>.
     */
    @Size(max = 255)
    public String getStatus() {
        return (String) get(8);
    }

    /**
     * Setter for <code>public.application_detail.batch_fk</code>.
     */
    public void setBatchFk(Long value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.application_detail.batch_fk</code>.
     */
    public Long getBatchFk() {
        return (Long) get(9);
    }

    /**
     * Setter for <code>public.application_detail.id</code>.
     */
    public void setId(Long value) {
        set(10, value);
    }

    /**
     * Getter for <code>public.application_detail.id</code>.
     */
    public Long getId() {
        return (Long) get(10);
    }

    /**
     * Setter for <code>public.application_detail.academic_year</code>.
     */
    public void setAcademicYear(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>public.application_detail.academic_year</code>.
     */
    @Size(max = 20)
    public String getAcademicYear() {
        return (String) get(11);
    }

    /**
     * Setter for <code>public.application_detail.campus_fk</code>.
     */
    public void setCampusFk(Long value) {
        set(12, value);
    }

    /**
     * Getter for <code>public.application_detail.campus_fk</code>.
     */
    public Long getCampusFk() {
        return (Long) get(12);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record13 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row13<String, String, String, String, Timestamp, String, String, Timestamp, String, Long, Long, String, Long> fieldsRow() {
        return (Row13) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row13<String, String, String, String, Timestamp, String, String, Timestamp, String, Long, Long, String, Long> valuesRow() {
        return (Row13) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return ApplicationDetail.APPLICATION_DETAIL.ADMISSION_OFFICER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return ApplicationDetail.APPLICATION_DETAIL.CODE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return ApplicationDetail.APPLICATION_DETAIL.COURSE_FK;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return ApplicationDetail.APPLICATION_DETAIL.FACULTY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field5() {
        return ApplicationDetail.APPLICATION_DETAIL.FINISH_DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return ApplicationDetail.APPLICATION_DETAIL.LOCATION_;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return ApplicationDetail.APPLICATION_DETAIL.MODE_OF_ATTENDANCE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field8() {
        return ApplicationDetail.APPLICATION_DETAIL.START_DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field9() {
        return ApplicationDetail.APPLICATION_DETAIL.STATUS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field10() {
        return ApplicationDetail.APPLICATION_DETAIL.BATCH_FK;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field11() {
        return ApplicationDetail.APPLICATION_DETAIL.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field12() {
        return ApplicationDetail.APPLICATION_DETAIL.ACADEMIC_YEAR;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field13() {
        return ApplicationDetail.APPLICATION_DETAIL.CAMPUS_FK;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getAdmissionOfficer();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getCode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getCourseFk();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getFaculty();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value5() {
        return getFinishDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getLocation_();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getModeOfAttendance();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value8() {
        return getStartDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value9() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value10() {
        return getBatchFk();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value11() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value12() {
        return getAcademicYear();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value13() {
        return getCampusFk();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ApplicationDetailRecord value1(String value) {
        setAdmissionOfficer(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ApplicationDetailRecord value2(String value) {
        setCode(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ApplicationDetailRecord value3(String value) {
        setCourseFk(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ApplicationDetailRecord value4(String value) {
        setFaculty(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ApplicationDetailRecord value5(Timestamp value) {
        setFinishDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ApplicationDetailRecord value6(String value) {
        setLocation_(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ApplicationDetailRecord value7(String value) {
        setModeOfAttendance(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ApplicationDetailRecord value8(Timestamp value) {
        setStartDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ApplicationDetailRecord value9(String value) {
        setStatus(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ApplicationDetailRecord value10(Long value) {
        setBatchFk(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ApplicationDetailRecord value11(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ApplicationDetailRecord value12(String value) {
        setAcademicYear(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ApplicationDetailRecord value13(Long value) {
        setCampusFk(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ApplicationDetailRecord values(String value1, String value2, String value3, String value4, Timestamp value5, String value6, String value7, Timestamp value8, String value9, Long value10, Long value11, String value12, Long value13) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ApplicationDetailRecord
     */
    public ApplicationDetailRecord() {
        super(ApplicationDetail.APPLICATION_DETAIL);
    }

    /**
     * Create a detached, initialised ApplicationDetailRecord
     */
    public ApplicationDetailRecord(String admissionOfficer, String code, String courseFk, String faculty, Timestamp finishDate, String location_, String modeOfAttendance, Timestamp startDate, String status, Long batchFk, Long id, String academicYear, Long campusFk) {
        super(ApplicationDetail.APPLICATION_DETAIL);

        set(0, admissionOfficer);
        set(1, code);
        set(2, courseFk);
        set(3, faculty);
        set(4, finishDate);
        set(5, location_);
        set(6, modeOfAttendance);
        set(7, startDate);
        set(8, status);
        set(9, batchFk);
        set(10, id);
        set(11, academicYear);
        set(12, campusFk);
    }
}
