/*
 * This file is generated by jOOQ.
*/
package schemas.public_.tables.records;


import java.sql.Timestamp;

import javax.annotation.Generated;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record10;
import org.jooq.Row10;
import org.jooq.impl.UpdatableRecordImpl;

import schemas.public_.tables.ApplicationUser;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ApplicationUserRecord extends UpdatableRecordImpl<ApplicationUserRecord> implements Record10<String, String, Boolean, String, Timestamp, Boolean, Long, String, String, Long> {

    private static final long serialVersionUID = 568937130;

    /**
     * Setter for <code>public.application_user.email</code>.
     */
    public void setEmail(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.application_user.email</code>.
     */
    @NotNull
    @Size(max = 50)
    public String getEmail() {
        return (String) get(0);
    }

    /**
     * Setter for <code>public.application_user.password_</code>.
     */
    public void setPassword_(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.application_user.password_</code>.
     */
    @Size(max = 100)
    public String getPassword_() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.application_user.is_active</code>.
     */
    public void setIsActive(Boolean value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.application_user.is_active</code>.
     */
    public Boolean getIsActive() {
        return (Boolean) get(2);
    }

    /**
     * Setter for <code>public.application_user.meta_data</code>.
     */
    public void setMetaData(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.application_user.meta_data</code>.
     */
    @Size(max = 100)
    public String getMetaData() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.application_user.last_update</code>.
     */
    public void setLastUpdate(Timestamp value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.application_user.last_update</code>.
     */
    public Timestamp getLastUpdate() {
        return (Timestamp) get(4);
    }

    /**
     * Setter for <code>public.application_user.is_admin</code>.
     */
    public void setIsAdmin(Boolean value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.application_user.is_admin</code>.
     */
    public Boolean getIsAdmin() {
        return (Boolean) get(5);
    }

    /**
     * Setter for <code>public.application_user.patient_fk</code>.
     */
    public void setPatientFk(Long value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.application_user.patient_fk</code>.
     */
    public Long getPatientFk() {
        return (Long) get(6);
    }

    /**
     * Setter for <code>public.application_user.name_</code>.
     */
    public void setName_(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.application_user.name_</code>.
     */
    @Size(max = 50)
    public String getName_() {
        return (String) get(7);
    }

    /**
     * Setter for <code>public.application_user.username</code>.
     */
    public void setUsername(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.application_user.username</code>.
     */
    @Size(max = 100)
    public String getUsername() {
        return (String) get(8);
    }

    /**
     * Setter for <code>public.application_user.id</code>.
     */
    public void setId(Long value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.application_user.id</code>.
     */
    public Long getId() {
        return (Long) get(9);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record10 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row10<String, String, Boolean, String, Timestamp, Boolean, Long, String, String, Long> fieldsRow() {
        return (Row10) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row10<String, String, Boolean, String, Timestamp, Boolean, Long, String, String, Long> valuesRow() {
        return (Row10) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return ApplicationUser.APPLICATION_USER.EMAIL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return ApplicationUser.APPLICATION_USER.PASSWORD_;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field3() {
        return ApplicationUser.APPLICATION_USER.IS_ACTIVE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return ApplicationUser.APPLICATION_USER.META_DATA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field5() {
        return ApplicationUser.APPLICATION_USER.LAST_UPDATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field6() {
        return ApplicationUser.APPLICATION_USER.IS_ADMIN;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field7() {
        return ApplicationUser.APPLICATION_USER.PATIENT_FK;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field8() {
        return ApplicationUser.APPLICATION_USER.NAME_;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field9() {
        return ApplicationUser.APPLICATION_USER.USERNAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field10() {
        return ApplicationUser.APPLICATION_USER.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getEmail();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getPassword_();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value3() {
        return getIsActive();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getMetaData();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value5() {
        return getLastUpdate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value6() {
        return getIsAdmin();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value7() {
        return getPatientFk();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value8() {
        return getName_();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value9() {
        return getUsername();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value10() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ApplicationUserRecord value1(String value) {
        setEmail(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ApplicationUserRecord value2(String value) {
        setPassword_(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ApplicationUserRecord value3(Boolean value) {
        setIsActive(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ApplicationUserRecord value4(String value) {
        setMetaData(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ApplicationUserRecord value5(Timestamp value) {
        setLastUpdate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ApplicationUserRecord value6(Boolean value) {
        setIsAdmin(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ApplicationUserRecord value7(Long value) {
        setPatientFk(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ApplicationUserRecord value8(String value) {
        setName_(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ApplicationUserRecord value9(String value) {
        setUsername(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ApplicationUserRecord value10(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ApplicationUserRecord values(String value1, String value2, Boolean value3, String value4, Timestamp value5, Boolean value6, Long value7, String value8, String value9, Long value10) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ApplicationUserRecord
     */
    public ApplicationUserRecord() {
        super(ApplicationUser.APPLICATION_USER);
    }

    /**
     * Create a detached, initialised ApplicationUserRecord
     */
    public ApplicationUserRecord(String email, String password_, Boolean isActive, String metaData, Timestamp lastUpdate, Boolean isAdmin, Long patientFk, String name_, String username, Long id) {
        super(ApplicationUser.APPLICATION_USER);

        set(0, email);
        set(1, password_);
        set(2, isActive);
        set(3, metaData);
        set(4, lastUpdate);
        set(5, isAdmin);
        set(6, patientFk);
        set(7, name_);
        set(8, username);
        set(9, id);
    }
}
