/*
 * This file is generated by jOOQ.
*/
package schemas.public_.tables.records;


import java.sql.Timestamp;

import javax.annotation.Generated;
import javax.validation.constraints.Size;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record13;
import org.jooq.Row13;
import org.jooq.impl.UpdatableRecordImpl;

import schemas.public_.tables.Classe;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ClasseRecord extends UpdatableRecordImpl<ClasseRecord> implements Record13<Long, String, Long, Long, String, Timestamp, Timestamp, Boolean, Long, Long, String, Long, Long> {

    private static final long serialVersionUID = 1053698817;

    /**
     * Setter for <code>public.classe.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.classe.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.classe.name_</code>.
     */
    public void setName_(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.classe.name_</code>.
     */
    @Size(max = 15)
    public String getName_() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.classe.class_type_fk</code>.
     */
    public void setClassTypeFk(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.classe.class_type_fk</code>.
     */
    public Long getClassTypeFk() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>public.classe.level_fk</code>.
     */
    public void setLevelFk(Long value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.classe.level_fk</code>.
     */
    public Long getLevelFk() {
        return (Long) get(3);
    }

    /**
     * Setter for <code>public.classe.description</code>.
     */
    public void setDescription(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.classe.description</code>.
     */
    @Size(max = 50)
    public String getDescription() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.classe.start_date</code>.
     */
    public void setStartDate(Timestamp value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.classe.start_date</code>.
     */
    public Timestamp getStartDate() {
        return (Timestamp) get(5);
    }

    /**
     * Setter for <code>public.classe.end_date</code>.
     */
    public void setEndDate(Timestamp value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.classe.end_date</code>.
     */
    public Timestamp getEndDate() {
        return (Timestamp) get(6);
    }

    /**
     * Setter for <code>public.classe.completed</code>.
     */
    public void setCompleted(Boolean value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.classe.completed</code>.
     */
    public Boolean getCompleted() {
        return (Boolean) get(7);
    }

    /**
     * Setter for <code>public.classe.student_number</code>.
     */
    public void setStudentNumber(Long value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.classe.student_number</code>.
     */
    public Long getStudentNumber() {
        return (Long) get(8);
    }

    /**
     * Setter for <code>public.classe.class_number</code>.
     */
    public void setClassNumber(Long value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.classe.class_number</code>.
     */
    public Long getClassNumber() {
        return (Long) get(9);
    }

    /**
     * Setter for <code>public.classe.student_no</code>.
     */
    public void setStudentNo(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>public.classe.student_no</code>.
     */
    @Size(max = 255)
    public String getStudentNo() {
        return (String) get(10);
    }

    /**
     * Setter for <code>public.classe.lecturer_fk</code>.
     */
    public void setLecturerFk(Long value) {
        set(11, value);
    }

    /**
     * Getter for <code>public.classe.lecturer_fk</code>.
     */
    public Long getLecturerFk() {
        return (Long) get(11);
    }

    /**
     * Setter for <code>public.classe.module_fk</code>.
     */
    public void setModuleFk(Long value) {
        set(12, value);
    }

    /**
     * Getter for <code>public.classe.module_fk</code>.
     */
    public Long getModuleFk() {
        return (Long) get(12);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record13 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row13<Long, String, Long, Long, String, Timestamp, Timestamp, Boolean, Long, Long, String, Long, Long> fieldsRow() {
        return (Row13) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row13<Long, String, Long, Long, String, Timestamp, Timestamp, Boolean, Long, Long, String, Long, Long> valuesRow() {
        return (Row13) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return Classe.CLASSE.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Classe.CLASSE.NAME_;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field3() {
        return Classe.CLASSE.CLASS_TYPE_FK;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field4() {
        return Classe.CLASSE.LEVEL_FK;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return Classe.CLASSE.DESCRIPTION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field6() {
        return Classe.CLASSE.START_DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field7() {
        return Classe.CLASSE.END_DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field8() {
        return Classe.CLASSE.COMPLETED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field9() {
        return Classe.CLASSE.STUDENT_NUMBER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field10() {
        return Classe.CLASSE.CLASS_NUMBER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field11() {
        return Classe.CLASSE.STUDENT_NO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field12() {
        return Classe.CLASSE.LECTURER_FK;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field13() {
        return Classe.CLASSE.MODULE_FK;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getName_();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value3() {
        return getClassTypeFk();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value4() {
        return getLevelFk();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getDescription();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value6() {
        return getStartDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value7() {
        return getEndDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value8() {
        return getCompleted();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value9() {
        return getStudentNumber();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value10() {
        return getClassNumber();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value11() {
        return getStudentNo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value12() {
        return getLecturerFk();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value13() {
        return getModuleFk();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ClasseRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ClasseRecord value2(String value) {
        setName_(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ClasseRecord value3(Long value) {
        setClassTypeFk(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ClasseRecord value4(Long value) {
        setLevelFk(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ClasseRecord value5(String value) {
        setDescription(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ClasseRecord value6(Timestamp value) {
        setStartDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ClasseRecord value7(Timestamp value) {
        setEndDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ClasseRecord value8(Boolean value) {
        setCompleted(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ClasseRecord value9(Long value) {
        setStudentNumber(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ClasseRecord value10(Long value) {
        setClassNumber(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ClasseRecord value11(String value) {
        setStudentNo(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ClasseRecord value12(Long value) {
        setLecturerFk(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ClasseRecord value13(Long value) {
        setModuleFk(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ClasseRecord values(Long value1, String value2, Long value3, Long value4, String value5, Timestamp value6, Timestamp value7, Boolean value8, Long value9, Long value10, String value11, Long value12, Long value13) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ClasseRecord
     */
    public ClasseRecord() {
        super(Classe.CLASSE);
    }

    /**
     * Create a detached, initialised ClasseRecord
     */
    public ClasseRecord(Long id, String name_, Long classTypeFk, Long levelFk, String description, Timestamp startDate, Timestamp endDate, Boolean completed, Long studentNumber, Long classNumber, String studentNo, Long lecturerFk, Long moduleFk) {
        super(Classe.CLASSE);

        set(0, id);
        set(1, name_);
        set(2, classTypeFk);
        set(3, levelFk);
        set(4, description);
        set(5, startDate);
        set(6, endDate);
        set(7, completed);
        set(8, studentNumber);
        set(9, classNumber);
        set(10, studentNo);
        set(11, lecturerFk);
        set(12, moduleFk);
    }
}
