/*
 * This file is generated by jOOQ.
*/
package schemas.public_.tables.records;


import java.math.BigDecimal;
import java.sql.Timestamp;

import javax.annotation.Generated;
import javax.validation.constraints.Size;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record9;
import org.jooq.Row9;
import org.jooq.impl.UpdatableRecordImpl;

import schemas.public_.tables.EducationalDetail;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class EducationalDetailRecord extends UpdatableRecordImpl<EducationalDetailRecord> implements Record9<Long, String, Long, Long, Timestamp, Timestamp, BigDecimal, Boolean, String> {

    private static final long serialVersionUID = 1216377584;

    /**
     * Setter for <code>public.educational_detail.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.educational_detail.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.educational_detail.institution_name</code>.
     */
    public void setInstitutionName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.educational_detail.institution_name</code>.
     */
    @Size(max = 50)
    public String getInstitutionName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.educational_detail.qualification_fk</code>.
     */
    public void setQualificationFk(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.educational_detail.qualification_fk</code>.
     */
    public Long getQualificationFk() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>public.educational_detail.subject_fk</code>.
     */
    public void setSubjectFk(Long value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.educational_detail.subject_fk</code>.
     */
    public Long getSubjectFk() {
        return (Long) get(3);
    }

    /**
     * Setter for <code>public.educational_detail.date_qualification_started</code>.
     */
    public void setDateQualificationStarted(Timestamp value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.educational_detail.date_qualification_started</code>.
     */
    public Timestamp getDateQualificationStarted() {
        return (Timestamp) get(4);
    }

    /**
     * Setter for <code>public.educational_detail.date_qualification_ended</code>.
     */
    public void setDateQualificationEnded(Timestamp value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.educational_detail.date_qualification_ended</code>.
     */
    public Timestamp getDateQualificationEnded() {
        return (Timestamp) get(5);
    }

    /**
     * Setter for <code>public.educational_detail.final_grade</code>.
     */
    public void setFinalGrade(BigDecimal value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.educational_detail.final_grade</code>.
     */
    public BigDecimal getFinalGrade() {
        return (BigDecimal) get(6);
    }

    /**
     * Setter for <code>public.educational_detail.completed</code>.
     */
    public void setCompleted(Boolean value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.educational_detail.completed</code>.
     */
    public Boolean getCompleted() {
        return (Boolean) get(7);
    }

    /**
     * Setter for <code>public.educational_detail.student_fk</code>.
     */
    public void setStudentFk(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.educational_detail.student_fk</code>.
     */
    @Size(max = 50)
    public String getStudentFk() {
        return (String) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record9 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row9<Long, String, Long, Long, Timestamp, Timestamp, BigDecimal, Boolean, String> fieldsRow() {
        return (Row9) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row9<Long, String, Long, Long, Timestamp, Timestamp, BigDecimal, Boolean, String> valuesRow() {
        return (Row9) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return EducationalDetail.EDUCATIONAL_DETAIL.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return EducationalDetail.EDUCATIONAL_DETAIL.INSTITUTION_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field3() {
        return EducationalDetail.EDUCATIONAL_DETAIL.QUALIFICATION_FK;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field4() {
        return EducationalDetail.EDUCATIONAL_DETAIL.SUBJECT_FK;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field5() {
        return EducationalDetail.EDUCATIONAL_DETAIL.DATE_QUALIFICATION_STARTED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field6() {
        return EducationalDetail.EDUCATIONAL_DETAIL.DATE_QUALIFICATION_ENDED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field7() {
        return EducationalDetail.EDUCATIONAL_DETAIL.FINAL_GRADE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field8() {
        return EducationalDetail.EDUCATIONAL_DETAIL.COMPLETED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field9() {
        return EducationalDetail.EDUCATIONAL_DETAIL.STUDENT_FK;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getInstitutionName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value3() {
        return getQualificationFk();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value4() {
        return getSubjectFk();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value5() {
        return getDateQualificationStarted();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value6() {
        return getDateQualificationEnded();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value7() {
        return getFinalGrade();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value8() {
        return getCompleted();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value9() {
        return getStudentFk();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EducationalDetailRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EducationalDetailRecord value2(String value) {
        setInstitutionName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EducationalDetailRecord value3(Long value) {
        setQualificationFk(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EducationalDetailRecord value4(Long value) {
        setSubjectFk(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EducationalDetailRecord value5(Timestamp value) {
        setDateQualificationStarted(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EducationalDetailRecord value6(Timestamp value) {
        setDateQualificationEnded(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EducationalDetailRecord value7(BigDecimal value) {
        setFinalGrade(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EducationalDetailRecord value8(Boolean value) {
        setCompleted(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EducationalDetailRecord value9(String value) {
        setStudentFk(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EducationalDetailRecord values(Long value1, String value2, Long value3, Long value4, Timestamp value5, Timestamp value6, BigDecimal value7, Boolean value8, String value9) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached EducationalDetailRecord
     */
    public EducationalDetailRecord() {
        super(EducationalDetail.EDUCATIONAL_DETAIL);
    }

    /**
     * Create a detached, initialised EducationalDetailRecord
     */
    public EducationalDetailRecord(Long id, String institutionName, Long qualificationFk, Long subjectFk, Timestamp dateQualificationStarted, Timestamp dateQualificationEnded, BigDecimal finalGrade, Boolean completed, String studentFk) {
        super(EducationalDetail.EDUCATIONAL_DETAIL);

        set(0, id);
        set(1, institutionName);
        set(2, qualificationFk);
        set(3, subjectFk);
        set(4, dateQualificationStarted);
        set(5, dateQualificationEnded);
        set(6, finalGrade);
        set(7, completed);
        set(8, studentFk);
    }
}
