/*
 * This file is generated by jOOQ.
*/
package schemas.public_.tables.records;


import javax.annotation.Generated;
import javax.validation.constraints.Size;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.UpdatableRecordImpl;

import schemas.public_.tables.EmergencyContact;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class EmergencyContactRecord extends UpdatableRecordImpl<EmergencyContactRecord> implements Record8<Long, Long, String, Long, String, String, String, String> {

    private static final long serialVersionUID = -1855084544;

    /**
     * Setter for <code>public.emergency_contact.phone</code>.
     */
    public void setPhone(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.emergency_contact.phone</code>.
     */
    public Long getPhone() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.emergency_contact.mobile</code>.
     */
    public void setMobile(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.emergency_contact.mobile</code>.
     */
    public Long getMobile() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>public.emergency_contact.email</code>.
     */
    public void setEmail(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.emergency_contact.email</code>.
     */
    @Size(max = 100)
    public String getEmail() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.emergency_contact.id</code>.
     */
    public void setId(Long value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.emergency_contact.id</code>.
     */
    public Long getId() {
        return (Long) get(3);
    }

    /**
     * Setter for <code>public.emergency_contact.full_name</code>.
     */
    public void setFullName(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.emergency_contact.full_name</code>.
     */
    @Size(max = 50)
    public String getFullName() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.emergency_contact.address</code>.
     */
    public void setAddress(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.emergency_contact.address</code>.
     */
    @Size(max = 50)
    public String getAddress() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.emergency_contact.relationship</code>.
     */
    public void setRelationship(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.emergency_contact.relationship</code>.
     */
    @Size(max = 25)
    public String getRelationship() {
        return (String) get(6);
    }

    /**
     * Setter for <code>public.emergency_contact.student_fk</code>.
     */
    public void setStudentFk(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.emergency_contact.student_fk</code>.
     */
    @Size(max = 50)
    public String getStudentFk() {
        return (String) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record8 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row8<Long, Long, String, Long, String, String, String, String> fieldsRow() {
        return (Row8) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row8<Long, Long, String, Long, String, String, String, String> valuesRow() {
        return (Row8) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return EmergencyContact.EMERGENCY_CONTACT.PHONE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field2() {
        return EmergencyContact.EMERGENCY_CONTACT.MOBILE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return EmergencyContact.EMERGENCY_CONTACT.EMAIL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field4() {
        return EmergencyContact.EMERGENCY_CONTACT.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return EmergencyContact.EMERGENCY_CONTACT.FULL_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return EmergencyContact.EMERGENCY_CONTACT.ADDRESS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return EmergencyContact.EMERGENCY_CONTACT.RELATIONSHIP;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field8() {
        return EmergencyContact.EMERGENCY_CONTACT.STUDENT_FK;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getPhone();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value2() {
        return getMobile();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getEmail();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value4() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getFullName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getAddress();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getRelationship();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value8() {
        return getStudentFk();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EmergencyContactRecord value1(Long value) {
        setPhone(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EmergencyContactRecord value2(Long value) {
        setMobile(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EmergencyContactRecord value3(String value) {
        setEmail(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EmergencyContactRecord value4(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EmergencyContactRecord value5(String value) {
        setFullName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EmergencyContactRecord value6(String value) {
        setAddress(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EmergencyContactRecord value7(String value) {
        setRelationship(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EmergencyContactRecord value8(String value) {
        setStudentFk(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EmergencyContactRecord values(Long value1, Long value2, String value3, Long value4, String value5, String value6, String value7, String value8) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached EmergencyContactRecord
     */
    public EmergencyContactRecord() {
        super(EmergencyContact.EMERGENCY_CONTACT);
    }

    /**
     * Create a detached, initialised EmergencyContactRecord
     */
    public EmergencyContactRecord(Long phone, Long mobile, String email, Long id, String fullName, String address, String relationship, String studentFk) {
        super(EmergencyContact.EMERGENCY_CONTACT);

        set(0, phone);
        set(1, mobile);
        set(2, email);
        set(3, id);
        set(4, fullName);
        set(5, address);
        set(6, relationship);
        set(7, studentFk);
    }
}
