/*
 * This file is generated by jOOQ.
*/
package schemas.public_.tables.records;


import java.sql.Timestamp;

import javax.annotation.Generated;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;

import schemas.public_.tables.InformationStatistic;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class InformationStatisticRecord extends UpdatableRecordImpl<InformationStatisticRecord> implements Record4<Long, String, String, Timestamp> {

    private static final long serialVersionUID = -1303488904;

    /**
     * Setter for <code>public.information_statistic.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.information_statistic.id</code>.
     */
    @NotNull
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.information_statistic.about_us</code>.
     */
    public void setAboutUs(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.information_statistic.about_us</code>.
     */
    @Size(max = 255)
    public String getAboutUs() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.information_statistic.other_about_us</code>.
     */
    public void setOtherAboutUs(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.information_statistic.other_about_us</code>.
     */
    @Size(max = 255)
    public String getOtherAboutUs() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.information_statistic.other_application</code>.
     */
    public void setOtherApplication(Timestamp value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.information_statistic.other_application</code>.
     */
    public Timestamp getOtherApplication() {
        return (Timestamp) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Long, String, String, Timestamp> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Long, String, String, Timestamp> valuesRow() {
        return (Row4) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return InformationStatistic.INFORMATION_STATISTIC.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return InformationStatistic.INFORMATION_STATISTIC.ABOUT_US;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return InformationStatistic.INFORMATION_STATISTIC.OTHER_ABOUT_US;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field4() {
        return InformationStatistic.INFORMATION_STATISTIC.OTHER_APPLICATION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getAboutUs();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getOtherAboutUs();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value4() {
        return getOtherApplication();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public InformationStatisticRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public InformationStatisticRecord value2(String value) {
        setAboutUs(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public InformationStatisticRecord value3(String value) {
        setOtherAboutUs(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public InformationStatisticRecord value4(Timestamp value) {
        setOtherApplication(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public InformationStatisticRecord values(Long value1, String value2, String value3, Timestamp value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached InformationStatisticRecord
     */
    public InformationStatisticRecord() {
        super(InformationStatistic.INFORMATION_STATISTIC);
    }

    /**
     * Create a detached, initialised InformationStatisticRecord
     */
    public InformationStatisticRecord(Long id, String aboutUs, String otherAboutUs, Timestamp otherApplication) {
        super(InformationStatistic.INFORMATION_STATISTIC);

        set(0, id);
        set(1, aboutUs);
        set(2, otherAboutUs);
        set(3, otherApplication);
    }
}
