/*
 * This file is generated by jOOQ.
*/
package schemas.public_.tables.records;


import java.sql.Timestamp;

import javax.annotation.Generated;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record20;
import org.jooq.Row20;
import org.jooq.impl.UpdatableRecordImpl;

import schemas.public_.tables.Institution;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class InstitutionRecord extends UpdatableRecordImpl<InstitutionRecord> implements Record20<Long, Timestamp, String, String, String, String, String, String, String, String, String, String, String, String, String, String, String, String, String, String> {

    private static final long serialVersionUID = -413013733;

    /**
     * Setter for <code>public.institution.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.institution.id</code>.
     */
    @NotNull
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.institution.created</code>.
     */
    public void setCreated(Timestamp value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.institution.created</code>.
     */
    public Timestamp getCreated() {
        return (Timestamp) get(1);
    }

    /**
     * Setter for <code>public.institution.industry</code>.
     */
    public void setIndustry(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.institution.industry</code>.
     */
    @Size(max = 255)
    public String getIndustry() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.institution.address</code>.
     */
    public void setAddress(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.institution.address</code>.
     */
    @Size(max = 255)
    public String getAddress() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.institution.city</code>.
     */
    public void setCity(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.institution.city</code>.
     */
    @Size(max = 255)
    public String getCity() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.institution.code</code>.
     */
    public void setCode(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.institution.code</code>.
     */
    @Size(max = 255)
    public String getCode() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.institution.country</code>.
     */
    public void setCountry(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.institution.country</code>.
     */
    @Size(max = 255)
    public String getCountry() {
        return (String) get(6);
    }

    /**
     * Setter for <code>public.institution.currency</code>.
     */
    public void setCurrency(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.institution.currency</code>.
     */
    @Size(max = 255)
    public String getCurrency() {
        return (String) get(7);
    }

    /**
     * Setter for <code>public.institution.email</code>.
     */
    public void setEmail(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.institution.email</code>.
     */
    @Size(max = 255)
    public String getEmail() {
        return (String) get(8);
    }

    /**
     * Setter for <code>public.institution.fax</code>.
     */
    public void setFax(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.institution.fax</code>.
     */
    @Size(max = 255)
    public String getFax() {
        return (String) get(9);
    }

    /**
     * Setter for <code>public.institution.language</code>.
     */
    public void setLanguage(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>public.institution.language</code>.
     */
    @Size(max = 255)
    public String getLanguage() {
        return (String) get(10);
    }

    /**
     * Setter for <code>public.institution.logo</code>.
     */
    public void setLogo(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>public.institution.logo</code>.
     */
    @Size(max = 255)
    public String getLogo() {
        return (String) get(11);
    }

    /**
     * Setter for <code>public.institution.mobile</code>.
     */
    public void setMobile(String value) {
        set(12, value);
    }

    /**
     * Getter for <code>public.institution.mobile</code>.
     */
    @Size(max = 255)
    public String getMobile() {
        return (String) get(12);
    }

    /**
     * Setter for <code>public.institution.name</code>.
     */
    public void setName(String value) {
        set(13, value);
    }

    /**
     * Getter for <code>public.institution.name</code>.
     */
    @Size(max = 255)
    public String getName() {
        return (String) get(13);
    }

    /**
     * Setter for <code>public.institution.phone</code>.
     */
    public void setPhone(String value) {
        set(14, value);
    }

    /**
     * Getter for <code>public.institution.phone</code>.
     */
    @Size(max = 255)
    public String getPhone() {
        return (String) get(14);
    }

    /**
     * Setter for <code>public.institution.postcode</code>.
     */
    public void setPostcode(String value) {
        set(15, value);
    }

    /**
     * Getter for <code>public.institution.postcode</code>.
     */
    @Size(max = 255)
    public String getPostcode() {
        return (String) get(15);
    }

    /**
     * Setter for <code>public.institution.region</code>.
     */
    public void setRegion(String value) {
        set(16, value);
    }

    /**
     * Getter for <code>public.institution.region</code>.
     */
    @Size(max = 255)
    public String getRegion() {
        return (String) get(16);
    }

    /**
     * Setter for <code>public.institution.timezone</code>.
     */
    public void setTimezone(String value) {
        set(17, value);
    }

    /**
     * Getter for <code>public.institution.timezone</code>.
     */
    @Size(max = 255)
    public String getTimezone() {
        return (String) get(17);
    }

    /**
     * Setter for <code>public.institution.website</code>.
     */
    public void setWebsite(String value) {
        set(18, value);
    }

    /**
     * Getter for <code>public.institution.website</code>.
     */
    @Size(max = 255)
    public String getWebsite() {
        return (String) get(18);
    }

    /**
     * Setter for <code>public.institution.status</code>.
     */
    public void setStatus(String value) {
        set(19, value);
    }

    /**
     * Getter for <code>public.institution.status</code>.
     */
    @Size(max = 255)
    public String getStatus() {
        return (String) get(19);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record20 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row20<Long, Timestamp, String, String, String, String, String, String, String, String, String, String, String, String, String, String, String, String, String, String> fieldsRow() {
        return (Row20) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row20<Long, Timestamp, String, String, String, String, String, String, String, String, String, String, String, String, String, String, String, String, String, String> valuesRow() {
        return (Row20) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return Institution.INSTITUTION.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field2() {
        return Institution.INSTITUTION.CREATED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Institution.INSTITUTION.INDUSTRY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return Institution.INSTITUTION.ADDRESS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return Institution.INSTITUTION.CITY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return Institution.INSTITUTION.CODE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return Institution.INSTITUTION.COUNTRY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field8() {
        return Institution.INSTITUTION.CURRENCY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field9() {
        return Institution.INSTITUTION.EMAIL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field10() {
        return Institution.INSTITUTION.FAX;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field11() {
        return Institution.INSTITUTION.LANGUAGE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field12() {
        return Institution.INSTITUTION.LOGO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field13() {
        return Institution.INSTITUTION.MOBILE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field14() {
        return Institution.INSTITUTION.NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field15() {
        return Institution.INSTITUTION.PHONE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field16() {
        return Institution.INSTITUTION.POSTCODE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field17() {
        return Institution.INSTITUTION.REGION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field18() {
        return Institution.INSTITUTION.TIMEZONE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field19() {
        return Institution.INSTITUTION.WEBSITE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field20() {
        return Institution.INSTITUTION.STATUS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value2() {
        return getCreated();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getIndustry();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getAddress();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getCity();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getCode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getCountry();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value8() {
        return getCurrency();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value9() {
        return getEmail();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value10() {
        return getFax();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value11() {
        return getLanguage();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value12() {
        return getLogo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value13() {
        return getMobile();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value14() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value15() {
        return getPhone();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value16() {
        return getPostcode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value17() {
        return getRegion();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value18() {
        return getTimezone();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value19() {
        return getWebsite();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value20() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public InstitutionRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public InstitutionRecord value2(Timestamp value) {
        setCreated(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public InstitutionRecord value3(String value) {
        setIndustry(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public InstitutionRecord value4(String value) {
        setAddress(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public InstitutionRecord value5(String value) {
        setCity(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public InstitutionRecord value6(String value) {
        setCode(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public InstitutionRecord value7(String value) {
        setCountry(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public InstitutionRecord value8(String value) {
        setCurrency(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public InstitutionRecord value9(String value) {
        setEmail(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public InstitutionRecord value10(String value) {
        setFax(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public InstitutionRecord value11(String value) {
        setLanguage(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public InstitutionRecord value12(String value) {
        setLogo(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public InstitutionRecord value13(String value) {
        setMobile(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public InstitutionRecord value14(String value) {
        setName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public InstitutionRecord value15(String value) {
        setPhone(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public InstitutionRecord value16(String value) {
        setPostcode(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public InstitutionRecord value17(String value) {
        setRegion(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public InstitutionRecord value18(String value) {
        setTimezone(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public InstitutionRecord value19(String value) {
        setWebsite(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public InstitutionRecord value20(String value) {
        setStatus(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public InstitutionRecord values(Long value1, Timestamp value2, String value3, String value4, String value5, String value6, String value7, String value8, String value9, String value10, String value11, String value12, String value13, String value14, String value15, String value16, String value17, String value18, String value19, String value20) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        value15(value15);
        value16(value16);
        value17(value17);
        value18(value18);
        value19(value19);
        value20(value20);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached InstitutionRecord
     */
    public InstitutionRecord() {
        super(Institution.INSTITUTION);
    }

    /**
     * Create a detached, initialised InstitutionRecord
     */
    public InstitutionRecord(Long id, Timestamp created, String industry, String address, String city, String code, String country, String currency, String email, String fax, String language, String logo, String mobile, String name, String phone, String postcode, String region, String timezone, String website, String status) {
        super(Institution.INSTITUTION);

        set(0, id);
        set(1, created);
        set(2, industry);
        set(3, address);
        set(4, city);
        set(5, code);
        set(6, country);
        set(7, currency);
        set(8, email);
        set(9, fax);
        set(10, language);
        set(11, logo);
        set(12, mobile);
        set(13, name);
        set(14, phone);
        set(15, postcode);
        set(16, region);
        set(17, timezone);
        set(18, website);
        set(19, status);
    }
}
