/*
 * This file is generated by jOOQ.
*/
package schemas.public_.tables.records;


import javax.annotation.Generated;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.UpdatableRecordImpl;

import schemas.public_.tables.ProfileInfo;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ProfileInfoRecord extends UpdatableRecordImpl<ProfileInfoRecord> implements Record8<Long, String, String, String, String, String, String, Long> {

    private static final long serialVersionUID = -1713881238;

    /**
     * Setter for <code>public.profile_info.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.profile_info.id</code>.
     */
    @NotNull
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.profile_info.created</code>.
     */
    public void setCreated(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.profile_info.created</code>.
     */
    @Size(max = 255)
    public String getCreated() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.profile_info.facebook_url</code>.
     */
    public void setFacebookUrl(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.profile_info.facebook_url</code>.
     */
    @Size(max = 255)
    public String getFacebookUrl() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.profile_info.favorite_game</code>.
     */
    public void setFavoriteGame(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.profile_info.favorite_game</code>.
     */
    @Size(max = 255)
    public String getFavoriteGame() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.profile_info.favorite_quran_reciter</code>.
     */
    public void setFavoriteQuranReciter(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.profile_info.favorite_quran_reciter</code>.
     */
    @Size(max = 255)
    public String getFavoriteQuranReciter() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.profile_info.linkedin_url</code>.
     */
    public void setLinkedinUrl(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.profile_info.linkedin_url</code>.
     */
    @Size(max = 255)
    public String getLinkedinUrl() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.profile_info.modified</code>.
     */
    public void setModified(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.profile_info.modified</code>.
     */
    @Size(max = 255)
    public String getModified() {
        return (String) get(6);
    }

    /**
     * Setter for <code>public.profile_info.student_fk</code>.
     */
    public void setStudentFk(Long value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.profile_info.student_fk</code>.
     */
    public Long getStudentFk() {
        return (Long) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record8 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row8<Long, String, String, String, String, String, String, Long> fieldsRow() {
        return (Row8) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row8<Long, String, String, String, String, String, String, Long> valuesRow() {
        return (Row8) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return ProfileInfo.PROFILE_INFO.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return ProfileInfo.PROFILE_INFO.CREATED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return ProfileInfo.PROFILE_INFO.FACEBOOK_URL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return ProfileInfo.PROFILE_INFO.FAVORITE_GAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return ProfileInfo.PROFILE_INFO.FAVORITE_QURAN_RECITER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return ProfileInfo.PROFILE_INFO.LINKEDIN_URL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return ProfileInfo.PROFILE_INFO.MODIFIED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field8() {
        return ProfileInfo.PROFILE_INFO.STUDENT_FK;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getCreated();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getFacebookUrl();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getFavoriteGame();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getFavoriteQuranReciter();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getLinkedinUrl();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getModified();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value8() {
        return getStudentFk();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProfileInfoRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProfileInfoRecord value2(String value) {
        setCreated(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProfileInfoRecord value3(String value) {
        setFacebookUrl(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProfileInfoRecord value4(String value) {
        setFavoriteGame(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProfileInfoRecord value5(String value) {
        setFavoriteQuranReciter(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProfileInfoRecord value6(String value) {
        setLinkedinUrl(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProfileInfoRecord value7(String value) {
        setModified(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProfileInfoRecord value8(Long value) {
        setStudentFk(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProfileInfoRecord values(Long value1, String value2, String value3, String value4, String value5, String value6, String value7, Long value8) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ProfileInfoRecord
     */
    public ProfileInfoRecord() {
        super(ProfileInfo.PROFILE_INFO);
    }

    /**
     * Create a detached, initialised ProfileInfoRecord
     */
    public ProfileInfoRecord(Long id, String created, String facebookUrl, String favoriteGame, String favoriteQuranReciter, String linkedinUrl, String modified, Long studentFk) {
        super(ProfileInfo.PROFILE_INFO);

        set(0, id);
        set(1, created);
        set(2, facebookUrl);
        set(3, favoriteGame);
        set(4, favoriteQuranReciter);
        set(5, linkedinUrl);
        set(6, modified);
        set(7, studentFk);
    }
}
