/*
 * This file is generated by jOOQ.
*/
package schemas.public_.tables.records;


import javax.annotation.Generated;

import org.jooq.impl.TableRecordImpl;

import schemas.public_.tables.UploadDocument;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UploadDocumentRecord extends TableRecordImpl<UploadDocumentRecord> {

    private static final long serialVersionUID = 1295268832;

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UploadDocumentRecord
     */
    public UploadDocumentRecord() {
        super(UploadDocument.UPLOAD_DOCUMENT);
    }
}
