/*
 * This file is generated by jOOQ.
*/
package schemas.referential.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;

import schemas.referential.Keys;
import schemas.referential.Referential;
import schemas.referential.tables.records.RDepartmentRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RDepartment extends TableImpl<RDepartmentRecord> {

    private static final long serialVersionUID = -1685500103;

    /**
     * The reference instance of <code>referential.r_department</code>
     */
    public static final RDepartment R_DEPARTMENT = new RDepartment();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<RDepartmentRecord> getRecordType() {
        return RDepartmentRecord.class;
    }

    /**
     * The column <code>referential.r_department.id</code>.
     */
    public final TableField<RDepartmentRecord, Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false).defaultValue(org.jooq.impl.DSL.field("nextval('referential.r_department_id_seq'::regclass)", org.jooq.impl.SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>referential.r_department.code</code>.
     */
    public final TableField<RDepartmentRecord, String> CODE = createField("code", org.jooq.impl.SQLDataType.VARCHAR.length(50), this, "");

    /**
     * The column <code>referential.r_department.department</code>.
     */
    public final TableField<RDepartmentRecord, String> DEPARTMENT = createField("department", org.jooq.impl.SQLDataType.VARCHAR.length(50), this, "");

    /**
     * The column <code>referential.r_department.description</code>.
     */
    public final TableField<RDepartmentRecord, String> DESCRIPTION = createField("description", org.jooq.impl.SQLDataType.VARCHAR.length(50), this, "");

    /**
     * Create a <code>referential.r_department</code> table reference
     */
    public RDepartment() {
        this("r_department", null);
    }

    /**
     * Create an aliased <code>referential.r_department</code> table reference
     */
    public RDepartment(String alias) {
        this(alias, R_DEPARTMENT);
    }

    private RDepartment(String alias, Table<RDepartmentRecord> aliased) {
        this(alias, aliased, null);
    }

    private RDepartment(String alias, Table<RDepartmentRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Referential.REFERENTIAL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<RDepartmentRecord, Long> getIdentity() {
        return Keys.IDENTITY_R_DEPARTMENT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<RDepartmentRecord> getPrimaryKey() {
        return Keys.R_DEPARTMENT_PK;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<RDepartmentRecord>> getKeys() {
        return Arrays.<UniqueKey<RDepartmentRecord>>asList(Keys.R_DEPARTMENT_PK);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RDepartment as(String alias) {
        return new RDepartment(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public RDepartment rename(String name) {
        return new RDepartment(name, null);
    }
}
