/*
 * This file is generated by jOOQ.
*/
package schemas.referential.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;

import schemas.referential.Keys;
import schemas.referential.Referential;
import schemas.referential.tables.records.RMonthRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RMonth extends TableImpl<RMonthRecord> {

    private static final long serialVersionUID = 384098744;

    /**
     * The reference instance of <code>referential.r_month</code>
     */
    public static final RMonth R_MONTH = new RMonth();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<RMonthRecord> getRecordType() {
        return RMonthRecord.class;
    }

    /**
     * The column <code>referential.r_month.id</code>.
     */
    public final TableField<RMonthRecord, Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false).defaultValue(org.jooq.impl.DSL.field("nextval('referential.r_month_id_seq'::regclass)", org.jooq.impl.SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>referential.r_month.month_</code>.
     */
    public final TableField<RMonthRecord, String> MONTH_ = createField("month_", org.jooq.impl.SQLDataType.CHAR.length(10), this, "");

    /**
     * Create a <code>referential.r_month</code> table reference
     */
    public RMonth() {
        this("r_month", null);
    }

    /**
     * Create an aliased <code>referential.r_month</code> table reference
     */
    public RMonth(String alias) {
        this(alias, R_MONTH);
    }

    private RMonth(String alias, Table<RMonthRecord> aliased) {
        this(alias, aliased, null);
    }

    private RMonth(String alias, Table<RMonthRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Referential.REFERENTIAL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<RMonthRecord, Long> getIdentity() {
        return Keys.IDENTITY_R_MONTH;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<RMonthRecord> getPrimaryKey() {
        return Keys.MONTH_PK;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<RMonthRecord>> getKeys() {
        return Arrays.<UniqueKey<RMonthRecord>>asList(Keys.MONTH_PK);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RMonth as(String alias) {
        return new RMonth(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public RMonth rename(String name) {
        return new RMonth(name, null);
    }
}
