/*
 * This file is generated by jOOQ.
*/
package schemas.referential;


import javax.annotation.Generated;

import org.jooq.Identity;
import org.jooq.UniqueKey;
import org.jooq.impl.AbstractKeys;

import schemas.referential.tables.RAttendanceOutcome;
import schemas.referential.tables.RAttendanceType;
import schemas.referential.tables.RCategory;
import schemas.referential.tables.RClassType;
import schemas.referential.tables.RContactPersonType;
import schemas.referential.tables.RCountry;
import schemas.referential.tables.RDropAttendanceReason;
import schemas.referential.tables.RDropTeachReason;
import schemas.referential.tables.RFee;
import schemas.referential.tables.RLevel;
import schemas.referential.tables.RProfil;
import schemas.referential.tables.RSyllabus;
import schemas.referential.tables.RTeachOutcome;
import schemas.referential.tables.RUser;
import schemas.referential.tables.records.RAttendanceOutcomeRecord;
import schemas.referential.tables.records.RAttendanceTypeRecord;
import schemas.referential.tables.records.RCategoryRecord;
import schemas.referential.tables.records.RClassTypeRecord;
import schemas.referential.tables.records.RContactPersonTypeRecord;
import schemas.referential.tables.records.RCountryRecord;
import schemas.referential.tables.records.RDropAttendanceReasonRecord;
import schemas.referential.tables.records.RDropTeachReasonRecord;
import schemas.referential.tables.records.RFeeRecord;
import schemas.referential.tables.records.RLevelRecord;
import schemas.referential.tables.records.RProfilRecord;
import schemas.referential.tables.records.RSyllabusRecord;
import schemas.referential.tables.records.RTeachOutcomeRecord;
import schemas.referential.tables.records.RUserRecord;


/**
 * A class modelling foreign key relationships between tables of the <code>referential</code> 
 * schema
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------

    public static final Identity<RAttendanceOutcomeRecord, Long> IDENTITY_R_ATTENDANCE_OUTCOME = Identities0.IDENTITY_R_ATTENDANCE_OUTCOME;
    public static final Identity<RAttendanceTypeRecord, Long> IDENTITY_R_ATTENDANCE_TYPE = Identities0.IDENTITY_R_ATTENDANCE_TYPE;
    public static final Identity<RCategoryRecord, Long> IDENTITY_R_CATEGORY = Identities0.IDENTITY_R_CATEGORY;
    public static final Identity<RClassTypeRecord, Long> IDENTITY_R_CLASS_TYPE = Identities0.IDENTITY_R_CLASS_TYPE;
    public static final Identity<RContactPersonTypeRecord, Long> IDENTITY_R_CONTACT_PERSON_TYPE = Identities0.IDENTITY_R_CONTACT_PERSON_TYPE;
    public static final Identity<RCountryRecord, Long> IDENTITY_R_COUNTRY = Identities0.IDENTITY_R_COUNTRY;
    public static final Identity<RDropAttendanceReasonRecord, Long> IDENTITY_R_DROP_ATTENDANCE_REASON = Identities0.IDENTITY_R_DROP_ATTENDANCE_REASON;
    public static final Identity<RDropTeachReasonRecord, Long> IDENTITY_R_DROP_TEACH_REASON = Identities0.IDENTITY_R_DROP_TEACH_REASON;
    public static final Identity<RFeeRecord, Long> IDENTITY_R_FEE = Identities0.IDENTITY_R_FEE;
    public static final Identity<RLevelRecord, Long> IDENTITY_R_LEVEL = Identities0.IDENTITY_R_LEVEL;
    public static final Identity<RProfilRecord, Long> IDENTITY_R_PROFIL = Identities0.IDENTITY_R_PROFIL;
    public static final Identity<RSyllabusRecord, Long> IDENTITY_R_SYLLABUS = Identities0.IDENTITY_R_SYLLABUS;
    public static final Identity<RTeachOutcomeRecord, Long> IDENTITY_R_TEACH_OUTCOME = Identities0.IDENTITY_R_TEACH_OUTCOME;
    public static final Identity<RUserRecord, Long> IDENTITY_R_USER = Identities0.IDENTITY_R_USER;

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<RAttendanceOutcomeRecord> R_ATTENDANCE_OUTCOME_PK = UniqueKeys0.R_ATTENDANCE_OUTCOME_PK;
    public static final UniqueKey<RAttendanceTypeRecord> R_ATTENDACE_TYPE_PK = UniqueKeys0.R_ATTENDACE_TYPE_PK;
    public static final UniqueKey<RCategoryRecord> R_CATEGORY_PK = UniqueKeys0.R_CATEGORY_PK;
    public static final UniqueKey<RClassTypeRecord> R_CLASS_TYPE_PK = UniqueKeys0.R_CLASS_TYPE_PK;
    public static final UniqueKey<RContactPersonTypeRecord> R_CONTACT_PERSON_TYPE_PK = UniqueKeys0.R_CONTACT_PERSON_TYPE_PK;
    public static final UniqueKey<RCountryRecord> R_COUNTRY_PK = UniqueKeys0.R_COUNTRY_PK;
    public static final UniqueKey<RDropAttendanceReasonRecord> R_DROP_ATTENDANCE_REASON_PK = UniqueKeys0.R_DROP_ATTENDANCE_REASON_PK;
    public static final UniqueKey<RDropTeachReasonRecord> R_DROP_TEACH_REASON_PK = UniqueKeys0.R_DROP_TEACH_REASON_PK;
    public static final UniqueKey<RFeeRecord> R_FEE_PK = UniqueKeys0.R_FEE_PK;
    public static final UniqueKey<RLevelRecord> R_LEVEL_PK = UniqueKeys0.R_LEVEL_PK;
    public static final UniqueKey<RProfilRecord> R_PROFIL_PKEY = UniqueKeys0.R_PROFIL_PKEY;
    public static final UniqueKey<RSyllabusRecord> R_SYLLABUS_NAME_PK = UniqueKeys0.R_SYLLABUS_NAME_PK;
    public static final UniqueKey<RTeachOutcomeRecord> R_TEACH_OUTCOME_PK = UniqueKeys0.R_TEACH_OUTCOME_PK;
    public static final UniqueKey<RUserRecord> R_USER_FK = UniqueKeys0.R_USER_FK;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Identities0 extends AbstractKeys {
        public static Identity<RAttendanceOutcomeRecord, Long> IDENTITY_R_ATTENDANCE_OUTCOME = createIdentity(RAttendanceOutcome.R_ATTENDANCE_OUTCOME, RAttendanceOutcome.R_ATTENDANCE_OUTCOME.ID);
        public static Identity<RAttendanceTypeRecord, Long> IDENTITY_R_ATTENDANCE_TYPE = createIdentity(RAttendanceType.R_ATTENDANCE_TYPE, RAttendanceType.R_ATTENDANCE_TYPE.ID);
        public static Identity<RCategoryRecord, Long> IDENTITY_R_CATEGORY = createIdentity(RCategory.R_CATEGORY, RCategory.R_CATEGORY.ID);
        public static Identity<RClassTypeRecord, Long> IDENTITY_R_CLASS_TYPE = createIdentity(RClassType.R_CLASS_TYPE, RClassType.R_CLASS_TYPE.ID);
        public static Identity<RContactPersonTypeRecord, Long> IDENTITY_R_CONTACT_PERSON_TYPE = createIdentity(RContactPersonType.R_CONTACT_PERSON_TYPE, RContactPersonType.R_CONTACT_PERSON_TYPE.ID);
        public static Identity<RCountryRecord, Long> IDENTITY_R_COUNTRY = createIdentity(RCountry.R_COUNTRY, RCountry.R_COUNTRY.ID);
        public static Identity<RDropAttendanceReasonRecord, Long> IDENTITY_R_DROP_ATTENDANCE_REASON = createIdentity(RDropAttendanceReason.R_DROP_ATTENDANCE_REASON, RDropAttendanceReason.R_DROP_ATTENDANCE_REASON.ID);
        public static Identity<RDropTeachReasonRecord, Long> IDENTITY_R_DROP_TEACH_REASON = createIdentity(RDropTeachReason.R_DROP_TEACH_REASON, RDropTeachReason.R_DROP_TEACH_REASON.ID);
        public static Identity<RFeeRecord, Long> IDENTITY_R_FEE = createIdentity(RFee.R_FEE, RFee.R_FEE.ID);
        public static Identity<RLevelRecord, Long> IDENTITY_R_LEVEL = createIdentity(RLevel.R_LEVEL, RLevel.R_LEVEL.ID);
        public static Identity<RProfilRecord, Long> IDENTITY_R_PROFIL = createIdentity(RProfil.R_PROFIL, RProfil.R_PROFIL.ID);
        public static Identity<RSyllabusRecord, Long> IDENTITY_R_SYLLABUS = createIdentity(RSyllabus.R_SYLLABUS, RSyllabus.R_SYLLABUS.ID);
        public static Identity<RTeachOutcomeRecord, Long> IDENTITY_R_TEACH_OUTCOME = createIdentity(RTeachOutcome.R_TEACH_OUTCOME, RTeachOutcome.R_TEACH_OUTCOME.ID);
        public static Identity<RUserRecord, Long> IDENTITY_R_USER = createIdentity(RUser.R_USER, RUser.R_USER.ID);
    }

    private static class UniqueKeys0 extends AbstractKeys {
        public static final UniqueKey<RAttendanceOutcomeRecord> R_ATTENDANCE_OUTCOME_PK = createUniqueKey(RAttendanceOutcome.R_ATTENDANCE_OUTCOME, "r_attendance_outcome_pk", RAttendanceOutcome.R_ATTENDANCE_OUTCOME.ID);
        public static final UniqueKey<RAttendanceTypeRecord> R_ATTENDACE_TYPE_PK = createUniqueKey(RAttendanceType.R_ATTENDANCE_TYPE, "r_attendace_type_pk", RAttendanceType.R_ATTENDANCE_TYPE.ID);
        public static final UniqueKey<RCategoryRecord> R_CATEGORY_PK = createUniqueKey(RCategory.R_CATEGORY, "r_category_pk", RCategory.R_CATEGORY.ID);
        public static final UniqueKey<RClassTypeRecord> R_CLASS_TYPE_PK = createUniqueKey(RClassType.R_CLASS_TYPE, "r_class_type_pk", RClassType.R_CLASS_TYPE.ID);
        public static final UniqueKey<RContactPersonTypeRecord> R_CONTACT_PERSON_TYPE_PK = createUniqueKey(RContactPersonType.R_CONTACT_PERSON_TYPE, "r_contact_person_type_pk", RContactPersonType.R_CONTACT_PERSON_TYPE.ID);
        public static final UniqueKey<RCountryRecord> R_COUNTRY_PK = createUniqueKey(RCountry.R_COUNTRY, "r_country_pk", RCountry.R_COUNTRY.ID);
        public static final UniqueKey<RDropAttendanceReasonRecord> R_DROP_ATTENDANCE_REASON_PK = createUniqueKey(RDropAttendanceReason.R_DROP_ATTENDANCE_REASON, "r_drop_attendance_reason_pk", RDropAttendanceReason.R_DROP_ATTENDANCE_REASON.ID);
        public static final UniqueKey<RDropTeachReasonRecord> R_DROP_TEACH_REASON_PK = createUniqueKey(RDropTeachReason.R_DROP_TEACH_REASON, "r_drop_teach_reason_pk", RDropTeachReason.R_DROP_TEACH_REASON.ID);
        public static final UniqueKey<RFeeRecord> R_FEE_PK = createUniqueKey(RFee.R_FEE, "r_fee_pk", RFee.R_FEE.ID);
        public static final UniqueKey<RLevelRecord> R_LEVEL_PK = createUniqueKey(RLevel.R_LEVEL, "r_level_pk", RLevel.R_LEVEL.ID);
        public static final UniqueKey<RProfilRecord> R_PROFIL_PKEY = createUniqueKey(RProfil.R_PROFIL, "r_profil_pkey", RProfil.R_PROFIL.ID);
        public static final UniqueKey<RSyllabusRecord> R_SYLLABUS_NAME_PK = createUniqueKey(RSyllabus.R_SYLLABUS, "r_syllabus_name_pk", RSyllabus.R_SYLLABUS.ID);
        public static final UniqueKey<RTeachOutcomeRecord> R_TEACH_OUTCOME_PK = createUniqueKey(RTeachOutcome.R_TEACH_OUTCOME, "r_teach_outcome_pk", RTeachOutcome.R_TEACH_OUTCOME.ID);
        public static final UniqueKey<RUserRecord> R_USER_FK = createUniqueKey(RUser.R_USER, "r_user_fk", RUser.R_USER.ID);
    }
}
