/*
 * This file is generated by jOOQ.
*/
package schemas.administrator.tables;


import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;

import schemas.administrator.Administrator;
import schemas.administrator.Keys;
import schemas.administrator.tables.records.ClassScheduleRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ClassSchedule extends TableImpl<ClassScheduleRecord> {

    private static final long serialVersionUID = -211013241;

    /**
     * The reference instance of <code>administrator.class_schedule</code>
     */
    public static final ClassSchedule CLASS_SCHEDULE = new ClassSchedule();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ClassScheduleRecord> getRecordType() {
        return ClassScheduleRecord.class;
    }

    /**
     * The column <code>administrator.class_schedule.id</code>.
     */
    public final TableField<ClassScheduleRecord, Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false).defaultValue(org.jooq.impl.DSL.field("nextval('administrator.class_schedule_id_seq'::regclass)", org.jooq.impl.SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>administrator.class_schedule.class_fk</code>.
     */
    public final TableField<ClassScheduleRecord, String> CLASS_FK = createField("class_fk", org.jooq.impl.SQLDataType.VARCHAR.length(15), this, "");

    /**
     * The column <code>administrator.class_schedule.start_time</code>.
     */
    public final TableField<ClassScheduleRecord, Timestamp> START_TIME = createField("start_time", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>administrator.class_schedule.end_time</code>.
     */
    public final TableField<ClassScheduleRecord, Timestamp> END_TIME = createField("end_time", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * Create a <code>administrator.class_schedule</code> table reference
     */
    public ClassSchedule() {
        this("class_schedule", null);
    }

    /**
     * Create an aliased <code>administrator.class_schedule</code> table reference
     */
    public ClassSchedule(String alias) {
        this(alias, CLASS_SCHEDULE);
    }

    private ClassSchedule(String alias, Table<ClassScheduleRecord> aliased) {
        this(alias, aliased, null);
    }

    private ClassSchedule(String alias, Table<ClassScheduleRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Administrator.ADMINISTRATOR;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<ClassScheduleRecord, Long> getIdentity() {
        return Keys.IDENTITY_CLASS_SCHEDULE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<ClassScheduleRecord> getPrimaryKey() {
        return Keys.CLASS_SCHEDULE_PK;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<ClassScheduleRecord>> getKeys() {
        return Arrays.<UniqueKey<ClassScheduleRecord>>asList(Keys.CLASS_SCHEDULE_PK);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ClassSchedule as(String alias) {
        return new ClassSchedule(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public ClassSchedule rename(String name) {
        return new ClassSchedule(name, null);
    }
}
