/*
 * This file is generated by jOOQ.
*/
package schemas.administrator.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;
import javax.validation.constraints.Size;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Teach implements Serializable {

    private static final long serialVersionUID = 1932832899;

    private Long      id;
    private String    instructorFk;
    private String    classFk;
    private Timestamp startDate;
    private Timestamp endDate;
    private Long      dropTeachReasonFk;
    private Long      teachOutcomeFk;

    public Teach() {}

    public Teach(Teach value) {
        this.id = value.id;
        this.instructorFk = value.instructorFk;
        this.classFk = value.classFk;
        this.startDate = value.startDate;
        this.endDate = value.endDate;
        this.dropTeachReasonFk = value.dropTeachReasonFk;
        this.teachOutcomeFk = value.teachOutcomeFk;
    }

    public Teach(
        Long      id,
        String    instructorFk,
        String    classFk,
        Timestamp startDate,
        Timestamp endDate,
        Long      dropTeachReasonFk,
        Long      teachOutcomeFk
    ) {
        this.id = id;
        this.instructorFk = instructorFk;
        this.classFk = classFk;
        this.startDate = startDate;
        this.endDate = endDate;
        this.dropTeachReasonFk = dropTeachReasonFk;
        this.teachOutcomeFk = teachOutcomeFk;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    @Size(max = 30)
    public String getInstructorFk() {
        return this.instructorFk;
    }

    public void setInstructorFk(String instructorFk) {
        this.instructorFk = instructorFk;
    }

    @Size(max = 10)
    public String getClassFk() {
        return this.classFk;
    }

    public void setClassFk(String classFk) {
        this.classFk = classFk;
    }

    public Timestamp getStartDate() {
        return this.startDate;
    }

    public void setStartDate(Timestamp startDate) {
        this.startDate = startDate;
    }

    public Timestamp getEndDate() {
        return this.endDate;
    }

    public void setEndDate(Timestamp endDate) {
        this.endDate = endDate;
    }

    public Long getDropTeachReasonFk() {
        return this.dropTeachReasonFk;
    }

    public void setDropTeachReasonFk(Long dropTeachReasonFk) {
        this.dropTeachReasonFk = dropTeachReasonFk;
    }

    public Long getTeachOutcomeFk() {
        return this.teachOutcomeFk;
    }

    public void setTeachOutcomeFk(Long teachOutcomeFk) {
        this.teachOutcomeFk = teachOutcomeFk;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Teach (");

        sb.append(id);
        sb.append(", ").append(instructorFk);
        sb.append(", ").append(classFk);
        sb.append(", ").append(startDate);
        sb.append(", ").append(endDate);
        sb.append(", ").append(dropTeachReasonFk);
        sb.append(", ").append(teachOutcomeFk);

        sb.append(")");
        return sb.toString();
    }
}
