/*
 * This file is generated by jOOQ.
*/
package schemas.administrator;


import javax.annotation.Generated;

import org.jooq.Sequence;
import org.jooq.impl.SequenceImpl;


/**
 * Convenience access to all sequences in administrator
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Sequences {

    /**
     * The sequence <code>administrator.application_user_id_seq</code>
     */
    public static final Sequence<Long> APPLICATION_USER_ID_SEQ = new SequenceImpl<Long>("application_user_id_seq", Administrator.ADMINISTRATOR, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>administrator.attendance_id_seq</code>
     */
    public static final Sequence<Long> ATTENDANCE_ID_SEQ = new SequenceImpl<Long>("attendance_id_seq", Administrator.ADMINISTRATOR, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>administrator.class_schedule_id_seq</code>
     */
    public static final Sequence<Long> CLASS_SCHEDULE_ID_SEQ = new SequenceImpl<Long>("class_schedule_id_seq", Administrator.ADMINISTRATOR, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>administrator.contact_person_student_id_seq</code>
     */
    public static final Sequence<Long> CONTACT_PERSON_STUDENT_ID_SEQ = new SequenceImpl<Long>("contact_person_student_id_seq", Administrator.ADMINISTRATOR, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>administrator.fee_student_id_seq</code>
     */
    public static final Sequence<Long> FEE_STUDENT_ID_SEQ = new SequenceImpl<Long>("fee_student_id_seq", Administrator.ADMINISTRATOR, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>administrator.fees_id_seq</code>
     */
    public static final Sequence<Long> FEES_ID_SEQ = new SequenceImpl<Long>("fees_id_seq", Administrator.ADMINISTRATOR, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>administrator.instructor_presence_id_seq</code>
     */
    public static final Sequence<Long> INSTRUCTOR_PRESENCE_ID_SEQ = new SequenceImpl<Long>("instructor_presence_id_seq", Administrator.ADMINISTRATOR, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>administrator.journee_id_seq</code>
     */
    public static final Sequence<Long> JOURNEE_ID_SEQ = new SequenceImpl<Long>("journee_id_seq", Administrator.ADMINISTRATOR, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>administrator.log_info_id_seq</code>
     */
    public static final Sequence<Long> LOG_INFO_ID_SEQ = new SequenceImpl<Long>("log_info_id_seq", Administrator.ADMINISTRATOR, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>administrator.r_academic_year_id_seq</code>
     */
    public static final Sequence<Long> R_ACADEMIC_YEAR_ID_SEQ = new SequenceImpl<Long>("r_academic_year_id_seq", Administrator.ADMINISTRATOR, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>administrator.ro_utilisateurs_id_seq</code>
     */
    public static final Sequence<Long> RO_UTILISATEURS_ID_SEQ = new SequenceImpl<Long>("ro_utilisateurs_id_seq", Administrator.ADMINISTRATOR, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>administrator.student_presence_id_seq</code>
     */
    public static final Sequence<Long> STUDENT_PRESENCE_ID_SEQ = new SequenceImpl<Long>("student_presence_id_seq", Administrator.ADMINISTRATOR, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>administrator.teach_id_seq</code>
     */
    public static final Sequence<Long> TEACH_ID_SEQ = new SequenceImpl<Long>("teach_id_seq", Administrator.ADMINISTRATOR, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>administrator.transaction_id_seq</code>
     */
    public static final Sequence<Long> TRANSACTION_ID_SEQ = new SequenceImpl<Long>("transaction_id_seq", Administrator.ADMINISTRATOR, org.jooq.impl.SQLDataType.BIGINT.nullable(false));
}
