/*
 * This file is generated by jOOQ.
*/
package schemas.referential.tables.records;


import javax.annotation.Generated;
import javax.validation.constraints.Size;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.UpdatableRecordImpl;

import schemas.referential.tables.RClassType;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RClassTypeRecord extends UpdatableRecordImpl<RClassTypeRecord> implements Record8<Long, String, String, Long, Boolean, Long, Long, Long> {

    private static final long serialVersionUID = 1965870053;

    /**
     * Setter for <code>referential.r_class_type.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>referential.r_class_type.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>referential.r_class_type.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>referential.r_class_type.name</code>.
     */
    @Size(max = 50)
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>referential.r_class_type.description</code>.
     */
    public void setDescription(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>referential.r_class_type.description</code>.
     */
    @Size(max = 50)
    public String getDescription() {
        return (String) get(2);
    }

    /**
     * Setter for <code>referential.r_class_type.max_weekly_classes</code>.
     */
    public void setMaxWeeklyClasses(Long value) {
        set(3, value);
    }

    /**
     * Getter for <code>referential.r_class_type.max_weekly_classes</code>.
     */
    public Long getMaxWeeklyClasses() {
        return (Long) get(3);
    }

    /**
     * Setter for <code>referential.r_class_type.exam</code>.
     */
    public void setExam(Boolean value) {
        set(4, value);
    }

    /**
     * Getter for <code>referential.r_class_type.exam</code>.
     */
    public Boolean getExam() {
        return (Boolean) get(4);
    }

    /**
     * Setter for <code>referential.r_class_type.minimum_attendance_percentage</code>.
     */
    public void setMinimumAttendancePercentage(Long value) {
        set(5, value);
    }

    /**
     * Getter for <code>referential.r_class_type.minimum_attendance_percentage</code>.
     */
    public Long getMinimumAttendancePercentage() {
        return (Long) get(5);
    }

    /**
     * Setter for <code>referential.r_class_type.attendance_type_fk</code>.
     */
    public void setAttendanceTypeFk(Long value) {
        set(6, value);
    }

    /**
     * Getter for <code>referential.r_class_type.attendance_type_fk</code>.
     */
    public Long getAttendanceTypeFk() {
        return (Long) get(6);
    }

    /**
     * Setter for <code>referential.r_class_type.total_working_days</code>.
     */
    public void setTotalWorkingDays(Long value) {
        set(7, value);
    }

    /**
     * Getter for <code>referential.r_class_type.total_working_days</code>.
     */
    public Long getTotalWorkingDays() {
        return (Long) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record8 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row8<Long, String, String, Long, Boolean, Long, Long, Long> fieldsRow() {
        return (Row8) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row8<Long, String, String, Long, Boolean, Long, Long, Long> valuesRow() {
        return (Row8) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return RClassType.R_CLASS_TYPE.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return RClassType.R_CLASS_TYPE.NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return RClassType.R_CLASS_TYPE.DESCRIPTION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field4() {
        return RClassType.R_CLASS_TYPE.MAX_WEEKLY_CLASSES;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field5() {
        return RClassType.R_CLASS_TYPE.EXAM;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field6() {
        return RClassType.R_CLASS_TYPE.MINIMUM_ATTENDANCE_PERCENTAGE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field7() {
        return RClassType.R_CLASS_TYPE.ATTENDANCE_TYPE_FK;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field8() {
        return RClassType.R_CLASS_TYPE.TOTAL_WORKING_DAYS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getDescription();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value4() {
        return getMaxWeeklyClasses();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value5() {
        return getExam();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value6() {
        return getMinimumAttendancePercentage();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value7() {
        return getAttendanceTypeFk();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value8() {
        return getTotalWorkingDays();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RClassTypeRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RClassTypeRecord value2(String value) {
        setName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RClassTypeRecord value3(String value) {
        setDescription(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RClassTypeRecord value4(Long value) {
        setMaxWeeklyClasses(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RClassTypeRecord value5(Boolean value) {
        setExam(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RClassTypeRecord value6(Long value) {
        setMinimumAttendancePercentage(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RClassTypeRecord value7(Long value) {
        setAttendanceTypeFk(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RClassTypeRecord value8(Long value) {
        setTotalWorkingDays(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RClassTypeRecord values(Long value1, String value2, String value3, Long value4, Boolean value5, Long value6, Long value7, Long value8) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached RClassTypeRecord
     */
    public RClassTypeRecord() {
        super(RClassType.R_CLASS_TYPE);
    }

    /**
     * Create a detached, initialised RClassTypeRecord
     */
    public RClassTypeRecord(Long id, String name, String description, Long maxWeeklyClasses, Boolean exam, Long minimumAttendancePercentage, Long attendanceTypeFk, Long totalWorkingDays) {
        super(RClassType.R_CLASS_TYPE);

        set(0, id);
        set(1, name);
        set(2, description);
        set(3, maxWeeklyClasses);
        set(4, exam);
        set(5, minimumAttendancePercentage);
        set(6, attendanceTypeFk);
        set(7, totalWorkingDays);
    }
}
