/*
 * This file is generated by jOOQ.
*/
package schemas.referential.tables.records;


import javax.annotation.Generated;
import javax.validation.constraints.Size;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;

import schemas.referential.tables.RDropTeachReason;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RDropTeachReasonRecord extends UpdatableRecordImpl<RDropTeachReasonRecord> implements Record2<Long, String> {

    private static final long serialVersionUID = -1246727437;

    /**
     * Setter for <code>referential.r_drop_teach_reason.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>referential.r_drop_teach_reason.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>referential.r_drop_teach_reason.reason</code>.
     */
    public void setReason(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>referential.r_drop_teach_reason.reason</code>.
     */
    @Size(max = 50)
    public String getReason() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<Long, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<Long, String> valuesRow() {
        return (Row2) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return RDropTeachReason.R_DROP_TEACH_REASON.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return RDropTeachReason.R_DROP_TEACH_REASON.REASON;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getReason();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RDropTeachReasonRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RDropTeachReasonRecord value2(String value) {
        setReason(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RDropTeachReasonRecord values(Long value1, String value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached RDropTeachReasonRecord
     */
    public RDropTeachReasonRecord() {
        super(RDropTeachReason.R_DROP_TEACH_REASON);
    }

    /**
     * Create a detached, initialised RDropTeachReasonRecord
     */
    public RDropTeachReasonRecord(Long id, String reason) {
        super(RDropTeachReason.R_DROP_TEACH_REASON);

        set(0, id);
        set(1, reason);
    }
}
