/*
 * This file is generated by jOOQ.
*/
package schemas.referential.tables.records;


import java.math.BigDecimal;

import javax.annotation.Generated;
import javax.validation.constraints.Size;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;

import schemas.referential.tables.RFee;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RFeeRecord extends UpdatableRecordImpl<RFeeRecord> implements Record4<Long, String, BigDecimal, String> {

    private static final long serialVersionUID = 310767617;

    /**
     * Setter for <code>referential.r_fee.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>referential.r_fee.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>referential.r_fee.fee_type</code>.
     */
    public void setFeeType(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>referential.r_fee.fee_type</code>.
     */
    @Size(max = 15)
    public String getFeeType() {
        return (String) get(1);
    }

    /**
     * Setter for <code>referential.r_fee.fees</code>.
     */
    public void setFees(BigDecimal value) {
        set(2, value);
    }

    /**
     * Getter for <code>referential.r_fee.fees</code>.
     */
    public BigDecimal getFees() {
        return (BigDecimal) get(2);
    }

    /**
     * Setter for <code>referential.r_fee.code</code>.
     */
    public void setCode(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>referential.r_fee.code</code>.
     */
    @Size(max = 10)
    public String getCode() {
        return (String) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Long, String, BigDecimal, String> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Long, String, BigDecimal, String> valuesRow() {
        return (Row4) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return RFee.R_FEE.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return RFee.R_FEE.FEE_TYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field3() {
        return RFee.R_FEE.FEES;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return RFee.R_FEE.CODE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getFeeType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value3() {
        return getFees();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getCode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RFeeRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RFeeRecord value2(String value) {
        setFeeType(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RFeeRecord value3(BigDecimal value) {
        setFees(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RFeeRecord value4(String value) {
        setCode(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RFeeRecord values(Long value1, String value2, BigDecimal value3, String value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached RFeeRecord
     */
    public RFeeRecord() {
        super(RFee.R_FEE);
    }

    /**
     * Create a detached, initialised RFeeRecord
     */
    public RFeeRecord(Long id, String feeType, BigDecimal fees, String code) {
        super(RFee.R_FEE);

        set(0, id);
        set(1, feeType);
        set(2, fees);
        set(3, code);
    }
}
