/*
 * This file is generated by jOOQ.
*/
package schemas.referential.tables.records;


import java.sql.Timestamp;

import javax.annotation.Generated;
import javax.validation.constraints.Size;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record11;
import org.jooq.Row11;
import org.jooq.impl.UpdatableRecordImpl;

import schemas.referential.tables.RUser;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RUserRecord extends UpdatableRecordImpl<RUserRecord> implements Record11<String, String, String, String, String, Timestamp, Timestamp, Timestamp, String, Long, String> {

    private static final long serialVersionUID = -1375968280;

    /**
     * Setter for <code>referential.r_user.email</code>.
     */
    public void setEmail(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>referential.r_user.email</code>.
     */
    @Size(max = 255)
    public String getEmail() {
        return (String) get(0);
    }

    /**
     * Setter for <code>referential.r_user.name_</code>.
     */
    public void setName_(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>referential.r_user.name_</code>.
     */
    @Size(max = 255)
    public String getName_() {
        return (String) get(1);
    }

    /**
     * Setter for <code>referential.r_user.password_</code>.
     */
    public void setPassword_(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>referential.r_user.password_</code>.
     */
    @Size(max = 255)
    public String getPassword_() {
        return (String) get(2);
    }

    /**
     * Setter for <code>referential.r_user.profil</code>.
     */
    public void setProfil(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>referential.r_user.profil</code>.
     */
    @Size(max = 255)
    public String getProfil() {
        return (String) get(3);
    }

    /**
     * Setter for <code>referential.r_user.status</code>.
     */
    public void setStatus(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>referential.r_user.status</code>.
     */
    @Size(max = 255)
    public String getStatus() {
        return (String) get(4);
    }

    /**
     * Setter for <code>referential.r_user.when_delete</code>.
     */
    public void setWhenDelete(Timestamp value) {
        set(5, value);
    }

    /**
     * Getter for <code>referential.r_user.when_delete</code>.
     */
    public Timestamp getWhenDelete() {
        return (Timestamp) get(5);
    }

    /**
     * Setter for <code>referential.r_user.when_done</code>.
     */
    public void setWhenDone(Timestamp value) {
        set(6, value);
    }

    /**
     * Getter for <code>referential.r_user.when_done</code>.
     */
    public Timestamp getWhenDone() {
        return (Timestamp) get(6);
    }

    /**
     * Setter for <code>referential.r_user.when_update</code>.
     */
    public void setWhenUpdate(Timestamp value) {
        set(7, value);
    }

    /**
     * Getter for <code>referential.r_user.when_update</code>.
     */
    public Timestamp getWhenUpdate() {
        return (Timestamp) get(7);
    }

    /**
     * Setter for <code>referential.r_user.who_done</code>.
     */
    public void setWhoDone(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>referential.r_user.who_done</code>.
     */
    @Size(max = 255)
    public String getWhoDone() {
        return (String) get(8);
    }

    /**
     * Setter for <code>referential.r_user.id</code>.
     */
    public void setId(Long value) {
        set(9, value);
    }

    /**
     * Getter for <code>referential.r_user.id</code>.
     */
    public Long getId() {
        return (Long) get(9);
    }

    /**
     * Setter for <code>referential.r_user.code</code>.
     */
    public void setCode(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>referential.r_user.code</code>.
     */
    @Size(max = 20)
    public String getCode() {
        return (String) get(10);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record11 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row11<String, String, String, String, String, Timestamp, Timestamp, Timestamp, String, Long, String> fieldsRow() {
        return (Row11) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row11<String, String, String, String, String, Timestamp, Timestamp, Timestamp, String, Long, String> valuesRow() {
        return (Row11) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return RUser.R_USER.EMAIL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return RUser.R_USER.NAME_;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return RUser.R_USER.PASSWORD_;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return RUser.R_USER.PROFIL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return RUser.R_USER.STATUS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field6() {
        return RUser.R_USER.WHEN_DELETE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field7() {
        return RUser.R_USER.WHEN_DONE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field8() {
        return RUser.R_USER.WHEN_UPDATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field9() {
        return RUser.R_USER.WHO_DONE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field10() {
        return RUser.R_USER.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field11() {
        return RUser.R_USER.CODE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getEmail();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getName_();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getPassword_();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getProfil();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value6() {
        return getWhenDelete();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value7() {
        return getWhenDone();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value8() {
        return getWhenUpdate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value9() {
        return getWhoDone();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value10() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value11() {
        return getCode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RUserRecord value1(String value) {
        setEmail(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RUserRecord value2(String value) {
        setName_(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RUserRecord value3(String value) {
        setPassword_(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RUserRecord value4(String value) {
        setProfil(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RUserRecord value5(String value) {
        setStatus(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RUserRecord value6(Timestamp value) {
        setWhenDelete(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RUserRecord value7(Timestamp value) {
        setWhenDone(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RUserRecord value8(Timestamp value) {
        setWhenUpdate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RUserRecord value9(String value) {
        setWhoDone(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RUserRecord value10(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RUserRecord value11(String value) {
        setCode(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RUserRecord values(String value1, String value2, String value3, String value4, String value5, Timestamp value6, Timestamp value7, Timestamp value8, String value9, Long value10, String value11) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached RUserRecord
     */
    public RUserRecord() {
        super(RUser.R_USER);
    }

    /**
     * Create a detached, initialised RUserRecord
     */
    public RUserRecord(String email, String name_, String password_, String profil, String status, Timestamp whenDelete, Timestamp whenDone, Timestamp whenUpdate, String whoDone, Long id, String code) {
        super(RUser.R_USER);

        set(0, email);
        set(1, name_);
        set(2, password_);
        set(3, profil);
        set(4, status);
        set(5, whenDelete);
        set(6, whenDone);
        set(7, whenUpdate);
        set(8, whoDone);
        set(9, id);
        set(10, code);
    }
}
