/*
 * This file is generated by jOOQ.
*/
package schemas.administrator.tables.records;


import java.sql.Timestamp;

import javax.annotation.Generated;
import javax.validation.constraints.Size;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;

import schemas.administrator.tables.StudentPresence;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class StudentPresenceRecord extends UpdatableRecordImpl<StudentPresenceRecord> implements Record6<String, String, Boolean, Timestamp, String, Long> {

    private static final long serialVersionUID = -1081252874;

    /**
     * Setter for <code>administrator.student_presence.student_fk</code>.
     */
    public void setStudentFk(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>administrator.student_presence.student_fk</code>.
     */
    @Size(max = 50)
    public String getStudentFk() {
        return (String) get(0);
    }

    /**
     * Setter for <code>administrator.student_presence.class_schedule_fk</code>.
     */
    public void setClassScheduleFk(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>administrator.student_presence.class_schedule_fk</code>.
     */
    @Size(max = 50)
    public String getClassScheduleFk() {
        return (String) get(1);
    }

    /**
     * Setter for <code>administrator.student_presence.present</code>.
     */
    public void setPresent(Boolean value) {
        set(2, value);
    }

    /**
     * Getter for <code>administrator.student_presence.present</code>.
     */
    public Boolean getPresent() {
        return (Boolean) get(2);
    }

    /**
     * Setter for <code>administrator.student_presence.dates</code>.
     */
    public void setDates(Timestamp value) {
        set(3, value);
    }

    /**
     * Getter for <code>administrator.student_presence.dates</code>.
     */
    public Timestamp getDates() {
        return (Timestamp) get(3);
    }

    /**
     * Setter for <code>administrator.student_presence.additional_info</code>.
     */
    public void setAdditionalInfo(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>administrator.student_presence.additional_info</code>.
     */
    @Size(max = 50)
    public String getAdditionalInfo() {
        return (String) get(4);
    }

    /**
     * Setter for <code>administrator.student_presence.id</code>.
     */
    public void setId(Long value) {
        set(5, value);
    }

    /**
     * Getter for <code>administrator.student_presence.id</code>.
     */
    public Long getId() {
        return (Long) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<String, String, Boolean, Timestamp, String, Long> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<String, String, Boolean, Timestamp, String, Long> valuesRow() {
        return (Row6) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return StudentPresence.STUDENT_PRESENCE.STUDENT_FK;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return StudentPresence.STUDENT_PRESENCE.CLASS_SCHEDULE_FK;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field3() {
        return StudentPresence.STUDENT_PRESENCE.PRESENT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field4() {
        return StudentPresence.STUDENT_PRESENCE.DATES;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return StudentPresence.STUDENT_PRESENCE.ADDITIONAL_INFO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field6() {
        return StudentPresence.STUDENT_PRESENCE.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getStudentFk();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getClassScheduleFk();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value3() {
        return getPresent();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value4() {
        return getDates();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getAdditionalInfo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value6() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StudentPresenceRecord value1(String value) {
        setStudentFk(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StudentPresenceRecord value2(String value) {
        setClassScheduleFk(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StudentPresenceRecord value3(Boolean value) {
        setPresent(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StudentPresenceRecord value4(Timestamp value) {
        setDates(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StudentPresenceRecord value5(String value) {
        setAdditionalInfo(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StudentPresenceRecord value6(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StudentPresenceRecord values(String value1, String value2, Boolean value3, Timestamp value4, String value5, Long value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached StudentPresenceRecord
     */
    public StudentPresenceRecord() {
        super(StudentPresence.STUDENT_PRESENCE);
    }

    /**
     * Create a detached, initialised StudentPresenceRecord
     */
    public StudentPresenceRecord(String studentFk, String classScheduleFk, Boolean present, Timestamp dates, String additionalInfo, Long id) {
        super(StudentPresence.STUDENT_PRESENCE);

        set(0, studentFk);
        set(1, classScheduleFk);
        set(2, present);
        set(3, dates);
        set(4, additionalInfo);
        set(5, id);
    }
}
