/*
 * This file is generated by jOOQ.
*/
package schemas.referential.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;
import javax.validation.constraints.Size;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RDepartment implements Serializable {

    private static final long serialVersionUID = 1137894867;

    private Long   id;
    private String code;
    private String department;
    private String description;

    public RDepartment() {}

    public RDepartment(RDepartment value) {
        this.id = value.id;
        this.code = value.code;
        this.department = value.department;
        this.description = value.description;
    }

    public RDepartment(
        Long   id,
        String code,
        String department,
        String description
    ) {
        this.id = id;
        this.code = code;
        this.department = department;
        this.description = description;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    @Size(max = 50)
    public String getCode() {
        return this.code;
    }

    public void setCode(String code) {
        this.code = code;
    }

    @Size(max = 50)
    public String getDepartment() {
        return this.department;
    }

    public void setDepartment(String department) {
        this.department = department;
    }

    @Size(max = 50)
    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("RDepartment (");

        sb.append(id);
        sb.append(", ").append(code);
        sb.append(", ").append(department);
        sb.append(", ").append(description);

        sb.append(")");
        return sb.toString();
    }
}
