/*
 * This file is generated by jOOQ.
*/
package schemas.referential.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;
import javax.validation.constraints.Size;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RMonth implements Serializable {

    private static final long serialVersionUID = -1496121619;

    private Long   id;
    private String month_;

    public RMonth() {}

    public RMonth(RMonth value) {
        this.id = value.id;
        this.month_ = value.month_;
    }

    public RMonth(
        Long   id,
        String month_
    ) {
        this.id = id;
        this.month_ = month_;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    @Size(max = 10)
    public String getMonth_() {
        return this.month_;
    }

    public void setMonth_(String month_) {
        this.month_ = month_;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("RMonth (");

        sb.append(id);
        sb.append(", ").append(month_);

        sb.append(")");
        return sb.toString();
    }
}
