/*
 * This file is generated by jOOQ.
*/
package schemas.referential.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;
import javax.validation.constraints.Size;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RStatus implements Serializable {

    private static final long serialVersionUID = 993192859;

    private Long   id;
    private String status;

    public RStatus() {}

    public RStatus(RStatus value) {
        this.id = value.id;
        this.status = value.status;
    }

    public RStatus(
        Long   id,
        String status
    ) {
        this.id = id;
        this.status = status;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    @Size(max = 20)
    public String getStatus() {
        return this.status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("RStatus (");

        sb.append(id);
        sb.append(", ").append(status);

        sb.append(")");
        return sb.toString();
    }
}
