/*
 * This file is generated by jOOQ.
*/
package schemas.public_.tables.daos;


import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;

import schemas.public_.tables.Finance;
import schemas.public_.tables.records.FinanceRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class FinanceDao extends DAOImpl<FinanceRecord, schemas.public_.tables.pojos.Finance, Long> {

    /**
     * Create a new FinanceDao without any configuration
     */
    public FinanceDao() {
        super(Finance.FINANCE, schemas.public_.tables.pojos.Finance.class);
    }

    /**
     * Create a new FinanceDao with an attached configuration
     */
    public FinanceDao(Configuration configuration) {
        super(Finance.FINANCE, schemas.public_.tables.pojos.Finance.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Long getId(schemas.public_.tables.pojos.Finance object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<schemas.public_.tables.pojos.Finance> fetchById(Long... values) {
        return fetch(Finance.FINANCE.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public schemas.public_.tables.pojos.Finance fetchOneById(Long value) {
        return fetchOne(Finance.FINANCE.ID, value);
    }

    /**
     * Fetch records that have <code>account_name IN (values)</code>
     */
    public List<schemas.public_.tables.pojos.Finance> fetchByAccountName(String... values) {
        return fetch(Finance.FINANCE.ACCOUNT_NAME, values);
    }

    /**
     * Fetch records that have <code>account_number IN (values)</code>
     */
    public List<schemas.public_.tables.pojos.Finance> fetchByAccountNumber(String... values) {
        return fetch(Finance.FINANCE.ACCOUNT_NUMBER, values);
    }

    /**
     * Fetch records that have <code>sort_code IN (values)</code>
     */
    public List<schemas.public_.tables.pojos.Finance> fetchBySortCode(String... values) {
        return fetch(Finance.FINANCE.SORT_CODE, values);
    }
}
