/*
 * This file is generated by jOOQ.
*/
package schemas.public_.tables.daos;


import java.sql.Timestamp;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;

import schemas.public_.tables.Institutionregistration;
import schemas.public_.tables.records.InstitutionregistrationRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class InstitutionregistrationDao extends DAOImpl<InstitutionregistrationRecord, schemas.public_.tables.pojos.Institutionregistration, Long> {

    /**
     * Create a new InstitutionregistrationDao without any configuration
     */
    public InstitutionregistrationDao() {
        super(Institutionregistration.INSTITUTIONREGISTRATION, schemas.public_.tables.pojos.Institutionregistration.class);
    }

    /**
     * Create a new InstitutionregistrationDao with an attached configuration
     */
    public InstitutionregistrationDao(Configuration configuration) {
        super(Institutionregistration.INSTITUTIONREGISTRATION, schemas.public_.tables.pojos.Institutionregistration.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Long getId(schemas.public_.tables.pojos.Institutionregistration object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<schemas.public_.tables.pojos.Institutionregistration> fetchById(Long... values) {
        return fetch(Institutionregistration.INSTITUTIONREGISTRATION.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public schemas.public_.tables.pojos.Institutionregistration fetchOneById(Long value) {
        return fetchOne(Institutionregistration.INSTITUTIONREGISTRATION.ID, value);
    }

    /**
     * Fetch records that have <code>abn IN (values)</code>
     */
    public List<schemas.public_.tables.pojos.Institutionregistration> fetchByAbn(String... values) {
        return fetch(Institutionregistration.INSTITUTIONREGISTRATION.ABN, values);
    }

    /**
     * Fetch records that have <code>address IN (values)</code>
     */
    public List<schemas.public_.tables.pojos.Institutionregistration> fetchByAddress(String... values) {
        return fetch(Institutionregistration.INSTITUTIONREGISTRATION.ADDRESS, values);
    }

    /**
     * Fetch records that have <code>business_email IN (values)</code>
     */
    public List<schemas.public_.tables.pojos.Institutionregistration> fetchByBusinessEmail(String... values) {
        return fetch(Institutionregistration.INSTITUTIONREGISTRATION.BUSINESS_EMAIL, values);
    }

    /**
     * Fetch records that have <code>business_name IN (values)</code>
     */
    public List<schemas.public_.tables.pojos.Institutionregistration> fetchByBusinessName(String... values) {
        return fetch(Institutionregistration.INSTITUTIONREGISTRATION.BUSINESS_NAME, values);
    }

    /**
     * Fetch records that have <code>business_phone IN (values)</code>
     */
    public List<schemas.public_.tables.pojos.Institutionregistration> fetchByBusinessPhone(String... values) {
        return fetch(Institutionregistration.INSTITUTIONREGISTRATION.BUSINESS_PHONE, values);
    }

    /**
     * Fetch records that have <code>business_size IN (values)</code>
     */
    public List<schemas.public_.tables.pojos.Institutionregistration> fetchByBusinessSize(String... values) {
        return fetch(Institutionregistration.INSTITUTIONREGISTRATION.BUSINESS_SIZE, values);
    }

    /**
     * Fetch records that have <code>business_website IN (values)</code>
     */
    public List<schemas.public_.tables.pojos.Institutionregistration> fetchByBusinessWebsite(String... values) {
        return fetch(Institutionregistration.INSTITUTIONREGISTRATION.BUSINESS_WEBSITE, values);
    }

    /**
     * Fetch records that have <code>city IN (values)</code>
     */
    public List<schemas.public_.tables.pojos.Institutionregistration> fetchByCity(String... values) {
        return fetch(Institutionregistration.INSTITUTIONREGISTRATION.CITY, values);
    }

    /**
     * Fetch records that have <code>country IN (values)</code>
     */
    public List<schemas.public_.tables.pojos.Institutionregistration> fetchByCountry(String... values) {
        return fetch(Institutionregistration.INSTITUTIONREGISTRATION.COUNTRY, values);
    }

    /**
     * Fetch records that have <code>created IN (values)</code>
     */
    public List<schemas.public_.tables.pojos.Institutionregistration> fetchByCreated(Timestamp... values) {
        return fetch(Institutionregistration.INSTITUTIONREGISTRATION.CREATED, values);
    }

    /**
     * Fetch records that have <code>current_advertisement IN (values)</code>
     */
    public List<schemas.public_.tables.pojos.Institutionregistration> fetchByCurrentAdvertisement(String... values) {
        return fetch(Institutionregistration.INSTITUTIONREGISTRATION.CURRENT_ADVERTISEMENT, values);
    }

    /**
     * Fetch records that have <code>email IN (values)</code>
     */
    public List<schemas.public_.tables.pojos.Institutionregistration> fetchByEmail(String... values) {
        return fetch(Institutionregistration.INSTITUTIONREGISTRATION.EMAIL, values);
    }

    /**
     * Fetch records that have <code>fax IN (values)</code>
     */
    public List<schemas.public_.tables.pojos.Institutionregistration> fetchByFax(String... values) {
        return fetch(Institutionregistration.INSTITUTIONREGISTRATION.FAX, values);
    }

    /**
     * Fetch records that have <code>first_name IN (values)</code>
     */
    public List<schemas.public_.tables.pojos.Institutionregistration> fetchByFirstName(String... values) {
        return fetch(Institutionregistration.INSTITUTIONREGISTRATION.FIRST_NAME, values);
    }

    /**
     * Fetch records that have <code>industry IN (values)</code>
     */
    public List<schemas.public_.tables.pojos.Institutionregistration> fetchByIndustry(String... values) {
        return fetch(Institutionregistration.INSTITUTIONREGISTRATION.INDUSTRY, values);
    }

    /**
     * Fetch records that have <code>last_name IN (values)</code>
     */
    public List<schemas.public_.tables.pojos.Institutionregistration> fetchByLastName(String... values) {
        return fetch(Institutionregistration.INSTITUTIONREGISTRATION.LAST_NAME, values);
    }

    /**
     * Fetch records that have <code>phone IN (values)</code>
     */
    public List<schemas.public_.tables.pojos.Institutionregistration> fetchByPhone(String... values) {
        return fetch(Institutionregistration.INSTITUTIONREGISTRATION.PHONE, values);
    }

    /**
     * Fetch records that have <code>postcode IN (values)</code>
     */
    public List<schemas.public_.tables.pojos.Institutionregistration> fetchByPostcode(String... values) {
        return fetch(Institutionregistration.INSTITUTIONREGISTRATION.POSTCODE, values);
    }

    /**
     * Fetch records that have <code>state IN (values)</code>
     */
    public List<schemas.public_.tables.pojos.Institutionregistration> fetchByState(String... values) {
        return fetch(Institutionregistration.INSTITUTIONREGISTRATION.STATE, values);
    }

    /**
     * Fetch records that have <code>status IN (values)</code>
     */
    public List<schemas.public_.tables.pojos.Institutionregistration> fetchByStatus(String... values) {
        return fetch(Institutionregistration.INSTITUTIONREGISTRATION.STATUS, values);
    }
}
