/*
 * This file is generated by jOOQ.
*/
package schemas.public_.tables.daos;


import java.sql.Timestamp;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;

import schemas.public_.tables.ParentInfo;
import schemas.public_.tables.records.ParentInfoRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ParentInfoDao extends DAOImpl<ParentInfoRecord, schemas.public_.tables.pojos.ParentInfo, Long> {

    /**
     * Create a new ParentInfoDao without any configuration
     */
    public ParentInfoDao() {
        super(ParentInfo.PARENT_INFO, schemas.public_.tables.pojos.ParentInfo.class);
    }

    /**
     * Create a new ParentInfoDao with an attached configuration
     */
    public ParentInfoDao(Configuration configuration) {
        super(ParentInfo.PARENT_INFO, schemas.public_.tables.pojos.ParentInfo.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Long getId(schemas.public_.tables.pojos.ParentInfo object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<schemas.public_.tables.pojos.ParentInfo> fetchById(Long... values) {
        return fetch(ParentInfo.PARENT_INFO.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public schemas.public_.tables.pojos.ParentInfo fetchOneById(Long value) {
        return fetchOne(ParentInfo.PARENT_INFO.ID, value);
    }

    /**
     * Fetch records that have <code>date_of_birth IN (values)</code>
     */
    public List<schemas.public_.tables.pojos.ParentInfo> fetchByDateOfBirth(Timestamp... values) {
        return fetch(ParentInfo.PARENT_INFO.DATE_OF_BIRTH, values);
    }

    /**
     * Fetch records that have <code>first_name IN (values)</code>
     */
    public List<schemas.public_.tables.pojos.ParentInfo> fetchByFirstName(String... values) {
        return fetch(ParentInfo.PARENT_INFO.FIRST_NAME, values);
    }

    /**
     * Fetch records that have <code>gender IN (values)</code>
     */
    public List<schemas.public_.tables.pojos.ParentInfo> fetchByGender(String... values) {
        return fetch(ParentInfo.PARENT_INFO.GENDER, values);
    }

    /**
     * Fetch records that have <code>last_name IN (values)</code>
     */
    public List<schemas.public_.tables.pojos.ParentInfo> fetchByLastName(String... values) {
        return fetch(ParentInfo.PARENT_INFO.LAST_NAME, values);
    }

    /**
     * Fetch records that have <code>other_info IN (values)</code>
     */
    public List<schemas.public_.tables.pojos.ParentInfo> fetchByOtherInfo(Timestamp... values) {
        return fetch(ParentInfo.PARENT_INFO.OTHER_INFO, values);
    }

    /**
     * Fetch records that have <code>student_fk IN (values)</code>
     */
    public List<schemas.public_.tables.pojos.ParentInfo> fetchByStudentFk(Long... values) {
        return fetch(ParentInfo.PARENT_INFO.STUDENT_FK, values);
    }
}
