/*
 * This file is generated by jOOQ.
*/
package schemas.referential.tables.daos;


import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;

import schemas.referential.tables.RCountry;
import schemas.referential.tables.records.RCountryRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RCountryDao extends DAOImpl<RCountryRecord, schemas.referential.tables.pojos.RCountry, Long> {

    /**
     * Create a new RCountryDao without any configuration
     */
    public RCountryDao() {
        super(RCountry.R_COUNTRY, schemas.referential.tables.pojos.RCountry.class);
    }

    /**
     * Create a new RCountryDao with an attached configuration
     */
    public RCountryDao(Configuration configuration) {
        super(RCountry.R_COUNTRY, schemas.referential.tables.pojos.RCountry.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Long getId(schemas.referential.tables.pojos.RCountry object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>iso IN (values)</code>
     */
    public List<schemas.referential.tables.pojos.RCountry> fetchByIso(String... values) {
        return fetch(RCountry.R_COUNTRY.ISO, values);
    }

    /**
     * Fetch records that have <code>name_ IN (values)</code>
     */
    public List<schemas.referential.tables.pojos.RCountry> fetchByName_(String... values) {
        return fetch(RCountry.R_COUNTRY.NAME_, values);
    }

    /**
     * Fetch records that have <code>nicename IN (values)</code>
     */
    public List<schemas.referential.tables.pojos.RCountry> fetchByNicename(String... values) {
        return fetch(RCountry.R_COUNTRY.NICENAME, values);
    }

    /**
     * Fetch records that have <code>iso3 IN (values)</code>
     */
    public List<schemas.referential.tables.pojos.RCountry> fetchByIso3(String... values) {
        return fetch(RCountry.R_COUNTRY.ISO3, values);
    }

    /**
     * Fetch records that have <code>numcode IN (values)</code>
     */
    public List<schemas.referential.tables.pojos.RCountry> fetchByNumcode(Long... values) {
        return fetch(RCountry.R_COUNTRY.NUMCODE, values);
    }

    /**
     * Fetch records that have <code>phonecode IN (values)</code>
     */
    public List<schemas.referential.tables.pojos.RCountry> fetchByPhonecode(Long... values) {
        return fetch(RCountry.R_COUNTRY.PHONECODE, values);
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<schemas.referential.tables.pojos.RCountry> fetchById(Long... values) {
        return fetch(RCountry.R_COUNTRY.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public schemas.referential.tables.pojos.RCountry fetchOneById(Long value) {
        return fetchOne(RCountry.R_COUNTRY.ID, value);
    }
}
