/*
 * This file is generated by jOOQ.
*/
package schemas.referential.tables.daos;


import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;

import schemas.referential.tables.RMonth;
import schemas.referential.tables.records.RMonthRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RMonthDao extends DAOImpl<RMonthRecord, schemas.referential.tables.pojos.RMonth, Long> {

    /**
     * Create a new RMonthDao without any configuration
     */
    public RMonthDao() {
        super(RMonth.R_MONTH, schemas.referential.tables.pojos.RMonth.class);
    }

    /**
     * Create a new RMonthDao with an attached configuration
     */
    public RMonthDao(Configuration configuration) {
        super(RMonth.R_MONTH, schemas.referential.tables.pojos.RMonth.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Long getId(schemas.referential.tables.pojos.RMonth object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<schemas.referential.tables.pojos.RMonth> fetchById(Long... values) {
        return fetch(RMonth.R_MONTH.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public schemas.referential.tables.pojos.RMonth fetchOneById(Long value) {
        return fetchOne(RMonth.R_MONTH.ID, value);
    }

    /**
     * Fetch records that have <code>month_ IN (values)</code>
     */
    public List<schemas.referential.tables.pojos.RMonth> fetchByMonth_(String... values) {
        return fetch(RMonth.R_MONTH.MONTH_, values);
    }
}
