/*
 * This file is generated by jOOQ.
*/
package schemas.public_.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;
import javax.validation.constraints.Size;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Address_ implements Serializable {

    private static final long serialVersionUID = -657209776;

    private Long   id;
    private String line_1;
    private String line_2;
    private String city;
    private String state;
    private Long   countryFk;
    private String otherDetail;

    public Address_() {}

    public Address_(Address_ value) {
        this.id = value.id;
        this.line_1 = value.line_1;
        this.line_2 = value.line_2;
        this.city = value.city;
        this.state = value.state;
        this.countryFk = value.countryFk;
        this.otherDetail = value.otherDetail;
    }

    public Address_(
        Long   id,
        String line_1,
        String line_2,
        String city,
        String state,
        Long   countryFk,
        String otherDetail
    ) {
        this.id = id;
        this.line_1 = line_1;
        this.line_2 = line_2;
        this.city = city;
        this.state = state;
        this.countryFk = countryFk;
        this.otherDetail = otherDetail;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    @Size(max = 100)
    public String getLine_1() {
        return this.line_1;
    }

    public void setLine_1(String line_1) {
        this.line_1 = line_1;
    }

    @Size(max = 100)
    public String getLine_2() {
        return this.line_2;
    }

    public void setLine_2(String line_2) {
        this.line_2 = line_2;
    }

    public String getCity() {
        return this.city;
    }

    public void setCity(String city) {
        this.city = city;
    }

    public String getState() {
        return this.state;
    }

    public void setState(String state) {
        this.state = state;
    }

    public Long getCountryFk() {
        return this.countryFk;
    }

    public void setCountryFk(Long countryFk) {
        this.countryFk = countryFk;
    }

    @Size(max = 100)
    public String getOtherDetail() {
        return this.otherDetail;
    }

    public void setOtherDetail(String otherDetail) {
        this.otherDetail = otherDetail;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Address_ (");

        sb.append(id);
        sb.append(", ").append(line_1);
        sb.append(", ").append(line_2);
        sb.append(", ").append(city);
        sb.append(", ").append(state);
        sb.append(", ").append(countryFk);
        sb.append(", ").append(otherDetail);

        sb.append(")");
        return sb.toString();
    }
}
