/*
 * This file is generated by jOOQ.
*/
package schemas.public_.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AddressDetail implements Serializable {

    private static final long serialVersionUID = -1672432819;

    private String    city;
    private String    postcode;
    private String    address;
    private String    region;
    private Long      id;
    private String    permanentAddress;
    private Long      primaryNumber;
    private Long      homeNumber;
    private String    email;
    private Long      countryFk;
    private String    presentAddress;
    private Timestamp validUntil;

    public AddressDetail() {}

    public AddressDetail(AddressDetail value) {
        this.city = value.city;
        this.postcode = value.postcode;
        this.address = value.address;
        this.region = value.region;
        this.id = value.id;
        this.permanentAddress = value.permanentAddress;
        this.primaryNumber = value.primaryNumber;
        this.homeNumber = value.homeNumber;
        this.email = value.email;
        this.countryFk = value.countryFk;
        this.presentAddress = value.presentAddress;
        this.validUntil = value.validUntil;
    }

    public AddressDetail(
        String    city,
        String    postcode,
        String    address,
        String    region,
        Long      id,
        String    permanentAddress,
        Long      primaryNumber,
        Long      homeNumber,
        String    email,
        Long      countryFk,
        String    presentAddress,
        Timestamp validUntil
    ) {
        this.city = city;
        this.postcode = postcode;
        this.address = address;
        this.region = region;
        this.id = id;
        this.permanentAddress = permanentAddress;
        this.primaryNumber = primaryNumber;
        this.homeNumber = homeNumber;
        this.email = email;
        this.countryFk = countryFk;
        this.presentAddress = presentAddress;
        this.validUntil = validUntil;
    }

    @Size(max = 255)
    public String getCity() {
        return this.city;
    }

    public void setCity(String city) {
        this.city = city;
    }

    @Size(max = 255)
    public String getPostcode() {
        return this.postcode;
    }

    public void setPostcode(String postcode) {
        this.postcode = postcode;
    }

    @Size(max = 255)
    public String getAddress() {
        return this.address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    @Size(max = 255)
    public String getRegion() {
        return this.region;
    }

    public void setRegion(String region) {
        this.region = region;
    }

    @NotNull
    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    @Size(max = 255)
    public String getPermanentAddress() {
        return this.permanentAddress;
    }

    public void setPermanentAddress(String permanentAddress) {
        this.permanentAddress = permanentAddress;
    }

    public Long getPrimaryNumber() {
        return this.primaryNumber;
    }

    public void setPrimaryNumber(Long primaryNumber) {
        this.primaryNumber = primaryNumber;
    }

    public Long getHomeNumber() {
        return this.homeNumber;
    }

    public void setHomeNumber(Long homeNumber) {
        this.homeNumber = homeNumber;
    }

    @Size(max = 50)
    public String getEmail() {
        return this.email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public Long getCountryFk() {
        return this.countryFk;
    }

    public void setCountryFk(Long countryFk) {
        this.countryFk = countryFk;
    }

    @Size(max = 255)
    public String getPresentAddress() {
        return this.presentAddress;
    }

    public void setPresentAddress(String presentAddress) {
        this.presentAddress = presentAddress;
    }

    public Timestamp getValidUntil() {
        return this.validUntil;
    }

    public void setValidUntil(Timestamp validUntil) {
        this.validUntil = validUntil;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("AddressDetail (");

        sb.append(city);
        sb.append(", ").append(postcode);
        sb.append(", ").append(address);
        sb.append(", ").append(region);
        sb.append(", ").append(id);
        sb.append(", ").append(permanentAddress);
        sb.append(", ").append(primaryNumber);
        sb.append(", ").append(homeNumber);
        sb.append(", ").append(email);
        sb.append(", ").append(countryFk);
        sb.append(", ").append(presentAddress);
        sb.append(", ").append(validUntil);

        sb.append(")");
        return sb.toString();
    }
}
