/*
 * This file is generated by jOOQ.
*/
package schemas.public_.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;
import javax.validation.constraints.Size;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ApplicationDetail implements Serializable {

    private static final long serialVersionUID = -180079792;

    private String    admissionOfficer;
    private String    code;
    private String    courseFk;
    private String    faculty;
    private Timestamp finishDate;
    private String    location_;
    private String    modeOfAttendance;
    private Timestamp startDate;
    private String    status;
    private Long      batchFk;
    private Long      id;
    private String    academicYear;
    private Long      campusFk;

    public ApplicationDetail() {}

    public ApplicationDetail(ApplicationDetail value) {
        this.admissionOfficer = value.admissionOfficer;
        this.code = value.code;
        this.courseFk = value.courseFk;
        this.faculty = value.faculty;
        this.finishDate = value.finishDate;
        this.location_ = value.location_;
        this.modeOfAttendance = value.modeOfAttendance;
        this.startDate = value.startDate;
        this.status = value.status;
        this.batchFk = value.batchFk;
        this.id = value.id;
        this.academicYear = value.academicYear;
        this.campusFk = value.campusFk;
    }

    public ApplicationDetail(
        String    admissionOfficer,
        String    code,
        String    courseFk,
        String    faculty,
        Timestamp finishDate,
        String    location_,
        String    modeOfAttendance,
        Timestamp startDate,
        String    status,
        Long      batchFk,
        Long      id,
        String    academicYear,
        Long      campusFk
    ) {
        this.admissionOfficer = admissionOfficer;
        this.code = code;
        this.courseFk = courseFk;
        this.faculty = faculty;
        this.finishDate = finishDate;
        this.location_ = location_;
        this.modeOfAttendance = modeOfAttendance;
        this.startDate = startDate;
        this.status = status;
        this.batchFk = batchFk;
        this.id = id;
        this.academicYear = academicYear;
        this.campusFk = campusFk;
    }

    @Size(max = 255)
    public String getAdmissionOfficer() {
        return this.admissionOfficer;
    }

    public void setAdmissionOfficer(String admissionOfficer) {
        this.admissionOfficer = admissionOfficer;
    }

    @Size(max = 255)
    public String getCode() {
        return this.code;
    }

    public void setCode(String code) {
        this.code = code;
    }

    @Size(max = 255)
    public String getCourseFk() {
        return this.courseFk;
    }

    public void setCourseFk(String courseFk) {
        this.courseFk = courseFk;
    }

    @Size(max = 255)
    public String getFaculty() {
        return this.faculty;
    }

    public void setFaculty(String faculty) {
        this.faculty = faculty;
    }

    public Timestamp getFinishDate() {
        return this.finishDate;
    }

    public void setFinishDate(Timestamp finishDate) {
        this.finishDate = finishDate;
    }

    @Size(max = 255)
    public String getLocation_() {
        return this.location_;
    }

    public void setLocation_(String location_) {
        this.location_ = location_;
    }

    @Size(max = 255)
    public String getModeOfAttendance() {
        return this.modeOfAttendance;
    }

    public void setModeOfAttendance(String modeOfAttendance) {
        this.modeOfAttendance = modeOfAttendance;
    }

    public Timestamp getStartDate() {
        return this.startDate;
    }

    public void setStartDate(Timestamp startDate) {
        this.startDate = startDate;
    }

    @Size(max = 255)
    public String getStatus() {
        return this.status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public Long getBatchFk() {
        return this.batchFk;
    }

    public void setBatchFk(Long batchFk) {
        this.batchFk = batchFk;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    @Size(max = 20)
    public String getAcademicYear() {
        return this.academicYear;
    }

    public void setAcademicYear(String academicYear) {
        this.academicYear = academicYear;
    }

    public Long getCampusFk() {
        return this.campusFk;
    }

    public void setCampusFk(Long campusFk) {
        this.campusFk = campusFk;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("ApplicationDetail (");

        sb.append(admissionOfficer);
        sb.append(", ").append(code);
        sb.append(", ").append(courseFk);
        sb.append(", ").append(faculty);
        sb.append(", ").append(finishDate);
        sb.append(", ").append(location_);
        sb.append(", ").append(modeOfAttendance);
        sb.append(", ").append(startDate);
        sb.append(", ").append(status);
        sb.append(", ").append(batchFk);
        sb.append(", ").append(id);
        sb.append(", ").append(academicYear);
        sb.append(", ").append(campusFk);

        sb.append(")");
        return sb.toString();
    }
}
