/*
 * This file is generated by jOOQ.
*/
package schemas.public_.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;
import javax.validation.constraints.Size;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Batch implements Serializable {

    private static final long serialVersionUID = 1002506283;

    private String    batchName;
    private Timestamp endDate;
    private Long      maxStudent;
    private Timestamp startDate;
    private Long      courseFk;
    private Long      id;
    private Long      courseId;

    public Batch() {}

    public Batch(Batch value) {
        this.batchName = value.batchName;
        this.endDate = value.endDate;
        this.maxStudent = value.maxStudent;
        this.startDate = value.startDate;
        this.courseFk = value.courseFk;
        this.id = value.id;
        this.courseId = value.courseId;
    }

    public Batch(
        String    batchName,
        Timestamp endDate,
        Long      maxStudent,
        Timestamp startDate,
        Long      courseFk,
        Long      id,
        Long      courseId
    ) {
        this.batchName = batchName;
        this.endDate = endDate;
        this.maxStudent = maxStudent;
        this.startDate = startDate;
        this.courseFk = courseFk;
        this.id = id;
        this.courseId = courseId;
    }

    @Size(max = 255)
    public String getBatchName() {
        return this.batchName;
    }

    public void setBatchName(String batchName) {
        this.batchName = batchName;
    }

    public Timestamp getEndDate() {
        return this.endDate;
    }

    public void setEndDate(Timestamp endDate) {
        this.endDate = endDate;
    }

    public Long getMaxStudent() {
        return this.maxStudent;
    }

    public void setMaxStudent(Long maxStudent) {
        this.maxStudent = maxStudent;
    }

    public Timestamp getStartDate() {
        return this.startDate;
    }

    public void setStartDate(Timestamp startDate) {
        this.startDate = startDate;
    }

    public Long getCourseFk() {
        return this.courseFk;
    }

    public void setCourseFk(Long courseFk) {
        this.courseFk = courseFk;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getCourseId() {
        return this.courseId;
    }

    public void setCourseId(Long courseId) {
        this.courseId = courseId;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Batch (");

        sb.append(batchName);
        sb.append(", ").append(endDate);
        sb.append(", ").append(maxStudent);
        sb.append(", ").append(startDate);
        sb.append(", ").append(courseFk);
        sb.append(", ").append(id);
        sb.append(", ").append(courseId);

        sb.append(")");
        return sb.toString();
    }
}
