/*
 * This file is generated by jOOQ.
*/
package schemas.public_.tables.pojos;


import java.io.Serializable;
import java.math.BigDecimal;
import java.sql.Timestamp;

import javax.annotation.Generated;
import javax.validation.constraints.Size;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class EducationalDetail implements Serializable {

    private static final long serialVersionUID = 597963773;

    private Long       id;
    private String     institutionName;
    private Long       qualificationFk;
    private Long       subjectFk;
    private Timestamp  dateQualificationStarted;
    private Timestamp  dateQualificationEnded;
    private BigDecimal finalGrade;
    private Boolean    completed;
    private String     studentFk;

    public EducationalDetail() {}

    public EducationalDetail(EducationalDetail value) {
        this.id = value.id;
        this.institutionName = value.institutionName;
        this.qualificationFk = value.qualificationFk;
        this.subjectFk = value.subjectFk;
        this.dateQualificationStarted = value.dateQualificationStarted;
        this.dateQualificationEnded = value.dateQualificationEnded;
        this.finalGrade = value.finalGrade;
        this.completed = value.completed;
        this.studentFk = value.studentFk;
    }

    public EducationalDetail(
        Long       id,
        String     institutionName,
        Long       qualificationFk,
        Long       subjectFk,
        Timestamp  dateQualificationStarted,
        Timestamp  dateQualificationEnded,
        BigDecimal finalGrade,
        Boolean    completed,
        String     studentFk
    ) {
        this.id = id;
        this.institutionName = institutionName;
        this.qualificationFk = qualificationFk;
        this.subjectFk = subjectFk;
        this.dateQualificationStarted = dateQualificationStarted;
        this.dateQualificationEnded = dateQualificationEnded;
        this.finalGrade = finalGrade;
        this.completed = completed;
        this.studentFk = studentFk;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    @Size(max = 50)
    public String getInstitutionName() {
        return this.institutionName;
    }

    public void setInstitutionName(String institutionName) {
        this.institutionName = institutionName;
    }

    public Long getQualificationFk() {
        return this.qualificationFk;
    }

    public void setQualificationFk(Long qualificationFk) {
        this.qualificationFk = qualificationFk;
    }

    public Long getSubjectFk() {
        return this.subjectFk;
    }

    public void setSubjectFk(Long subjectFk) {
        this.subjectFk = subjectFk;
    }

    public Timestamp getDateQualificationStarted() {
        return this.dateQualificationStarted;
    }

    public void setDateQualificationStarted(Timestamp dateQualificationStarted) {
        this.dateQualificationStarted = dateQualificationStarted;
    }

    public Timestamp getDateQualificationEnded() {
        return this.dateQualificationEnded;
    }

    public void setDateQualificationEnded(Timestamp dateQualificationEnded) {
        this.dateQualificationEnded = dateQualificationEnded;
    }

    public BigDecimal getFinalGrade() {
        return this.finalGrade;
    }

    public void setFinalGrade(BigDecimal finalGrade) {
        this.finalGrade = finalGrade;
    }

    public Boolean getCompleted() {
        return this.completed;
    }

    public void setCompleted(Boolean completed) {
        this.completed = completed;
    }

    @Size(max = 50)
    public String getStudentFk() {
        return this.studentFk;
    }

    public void setStudentFk(String studentFk) {
        this.studentFk = studentFk;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("EducationalDetail (");

        sb.append(id);
        sb.append(", ").append(institutionName);
        sb.append(", ").append(qualificationFk);
        sb.append(", ").append(subjectFk);
        sb.append(", ").append(dateQualificationStarted);
        sb.append(", ").append(dateQualificationEnded);
        sb.append(", ").append(finalGrade);
        sb.append(", ").append(completed);
        sb.append(", ").append(studentFk);

        sb.append(")");
        return sb.toString();
    }
}
