/*
 * This file is generated by jOOQ.
*/
package schemas.public_.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Experience implements Serializable {

    private static final long serialVersionUID = -951656452;

    private Long   id;
    private String city;
    private String country;
    private String employerAddress;
    private String employerName;
    private String endDate;
    private String jobTitle;
    private String responsibilities;
    private String startDate;

    public Experience() {}

    public Experience(Experience value) {
        this.id = value.id;
        this.city = value.city;
        this.country = value.country;
        this.employerAddress = value.employerAddress;
        this.employerName = value.employerName;
        this.endDate = value.endDate;
        this.jobTitle = value.jobTitle;
        this.responsibilities = value.responsibilities;
        this.startDate = value.startDate;
    }

    public Experience(
        Long   id,
        String city,
        String country,
        String employerAddress,
        String employerName,
        String endDate,
        String jobTitle,
        String responsibilities,
        String startDate
    ) {
        this.id = id;
        this.city = city;
        this.country = country;
        this.employerAddress = employerAddress;
        this.employerName = employerName;
        this.endDate = endDate;
        this.jobTitle = jobTitle;
        this.responsibilities = responsibilities;
        this.startDate = startDate;
    }

    @NotNull
    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    @Size(max = 255)
    public String getCity() {
        return this.city;
    }

    public void setCity(String city) {
        this.city = city;
    }

    @Size(max = 255)
    public String getCountry() {
        return this.country;
    }

    public void setCountry(String country) {
        this.country = country;
    }

    @Size(max = 255)
    public String getEmployerAddress() {
        return this.employerAddress;
    }

    public void setEmployerAddress(String employerAddress) {
        this.employerAddress = employerAddress;
    }

    @Size(max = 255)
    public String getEmployerName() {
        return this.employerName;
    }

    public void setEmployerName(String employerName) {
        this.employerName = employerName;
    }

    @Size(max = 255)
    public String getEndDate() {
        return this.endDate;
    }

    public void setEndDate(String endDate) {
        this.endDate = endDate;
    }

    @Size(max = 255)
    public String getJobTitle() {
        return this.jobTitle;
    }

    public void setJobTitle(String jobTitle) {
        this.jobTitle = jobTitle;
    }

    @Size(max = 255)
    public String getResponsibilities() {
        return this.responsibilities;
    }

    public void setResponsibilities(String responsibilities) {
        this.responsibilities = responsibilities;
    }

    @Size(max = 255)
    public String getStartDate() {
        return this.startDate;
    }

    public void setStartDate(String startDate) {
        this.startDate = startDate;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Experience (");

        sb.append(id);
        sb.append(", ").append(city);
        sb.append(", ").append(country);
        sb.append(", ").append(employerAddress);
        sb.append(", ").append(employerName);
        sb.append(", ").append(endDate);
        sb.append(", ").append(jobTitle);
        sb.append(", ").append(responsibilities);
        sb.append(", ").append(startDate);

        sb.append(")");
        return sb.toString();
    }
}
