/*
 * This file is generated by jOOQ.
*/
package schemas.public_.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Finance implements Serializable {

    private static final long serialVersionUID = -984151974;

    private Long   id;
    private String accountName;
    private String accountNumber;
    private String sortCode;

    public Finance() {}

    public Finance(Finance value) {
        this.id = value.id;
        this.accountName = value.accountName;
        this.accountNumber = value.accountNumber;
        this.sortCode = value.sortCode;
    }

    public Finance(
        Long   id,
        String accountName,
        String accountNumber,
        String sortCode
    ) {
        this.id = id;
        this.accountName = accountName;
        this.accountNumber = accountNumber;
        this.sortCode = sortCode;
    }

    @NotNull
    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    @Size(max = 255)
    public String getAccountName() {
        return this.accountName;
    }

    public void setAccountName(String accountName) {
        this.accountName = accountName;
    }

    @Size(max = 255)
    public String getAccountNumber() {
        return this.accountNumber;
    }

    public void setAccountNumber(String accountNumber) {
        this.accountNumber = accountNumber;
    }

    @Size(max = 255)
    public String getSortCode() {
        return this.sortCode;
    }

    public void setSortCode(String sortCode) {
        this.sortCode = sortCode;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Finance (");

        sb.append(id);
        sb.append(", ").append(accountName);
        sb.append(", ").append(accountNumber);
        sb.append(", ").append(sortCode);

        sb.append(")");
        return sb.toString();
    }
}
