/*
 * This file is generated by jOOQ.
*/
package schemas.public_.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class InformationStatistic implements Serializable {

    private static final long serialVersionUID = -208966462;

    private Long      id;
    private String    aboutUs;
    private String    otherAboutUs;
    private Timestamp otherApplication;

    public InformationStatistic() {}

    public InformationStatistic(InformationStatistic value) {
        this.id = value.id;
        this.aboutUs = value.aboutUs;
        this.otherAboutUs = value.otherAboutUs;
        this.otherApplication = value.otherApplication;
    }

    public InformationStatistic(
        Long      id,
        String    aboutUs,
        String    otherAboutUs,
        Timestamp otherApplication
    ) {
        this.id = id;
        this.aboutUs = aboutUs;
        this.otherAboutUs = otherAboutUs;
        this.otherApplication = otherApplication;
    }

    @NotNull
    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    @Size(max = 255)
    public String getAboutUs() {
        return this.aboutUs;
    }

    public void setAboutUs(String aboutUs) {
        this.aboutUs = aboutUs;
    }

    @Size(max = 255)
    public String getOtherAboutUs() {
        return this.otherAboutUs;
    }

    public void setOtherAboutUs(String otherAboutUs) {
        this.otherAboutUs = otherAboutUs;
    }

    public Timestamp getOtherApplication() {
        return this.otherApplication;
    }

    public void setOtherApplication(Timestamp otherApplication) {
        this.otherApplication = otherApplication;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("InformationStatistic (");

        sb.append(id);
        sb.append(", ").append(aboutUs);
        sb.append(", ").append(otherAboutUs);
        sb.append(", ").append(otherApplication);

        sb.append(")");
        return sb.toString();
    }
}
