/*
 * This file is generated by jOOQ.
*/
package schemas.public_.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;
import javax.validation.constraints.Size;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class NationalityDetail implements Serializable {

    private static final long serialVersionUID = 568808668;

    private Long      id;
    private Long      nationalityFk;
    private Long      permanentResidenceFk;
    private Long      residentialStatusFk;
    private String    studentFk;
    private String    passportNo;
    private Timestamp issueDate;
    private Timestamp expiryDate;
    private String    issuePlace;
    private String    nameOnPassport;
    private Long      identificationTypeFk;

    public NationalityDetail() {}

    public NationalityDetail(NationalityDetail value) {
        this.id = value.id;
        this.nationalityFk = value.nationalityFk;
        this.permanentResidenceFk = value.permanentResidenceFk;
        this.residentialStatusFk = value.residentialStatusFk;
        this.studentFk = value.studentFk;
        this.passportNo = value.passportNo;
        this.issueDate = value.issueDate;
        this.expiryDate = value.expiryDate;
        this.issuePlace = value.issuePlace;
        this.nameOnPassport = value.nameOnPassport;
        this.identificationTypeFk = value.identificationTypeFk;
    }

    public NationalityDetail(
        Long      id,
        Long      nationalityFk,
        Long      permanentResidenceFk,
        Long      residentialStatusFk,
        String    studentFk,
        String    passportNo,
        Timestamp issueDate,
        Timestamp expiryDate,
        String    issuePlace,
        String    nameOnPassport,
        Long      identificationTypeFk
    ) {
        this.id = id;
        this.nationalityFk = nationalityFk;
        this.permanentResidenceFk = permanentResidenceFk;
        this.residentialStatusFk = residentialStatusFk;
        this.studentFk = studentFk;
        this.passportNo = passportNo;
        this.issueDate = issueDate;
        this.expiryDate = expiryDate;
        this.issuePlace = issuePlace;
        this.nameOnPassport = nameOnPassport;
        this.identificationTypeFk = identificationTypeFk;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getNationalityFk() {
        return this.nationalityFk;
    }

    public void setNationalityFk(Long nationalityFk) {
        this.nationalityFk = nationalityFk;
    }

    public Long getPermanentResidenceFk() {
        return this.permanentResidenceFk;
    }

    public void setPermanentResidenceFk(Long permanentResidenceFk) {
        this.permanentResidenceFk = permanentResidenceFk;
    }

    public Long getResidentialStatusFk() {
        return this.residentialStatusFk;
    }

    public void setResidentialStatusFk(Long residentialStatusFk) {
        this.residentialStatusFk = residentialStatusFk;
    }

    @Size(max = 50)
    public String getStudentFk() {
        return this.studentFk;
    }

    public void setStudentFk(String studentFk) {
        this.studentFk = studentFk;
    }

    @Size(max = 50)
    public String getPassportNo() {
        return this.passportNo;
    }

    public void setPassportNo(String passportNo) {
        this.passportNo = passportNo;
    }

    public Timestamp getIssueDate() {
        return this.issueDate;
    }

    public void setIssueDate(Timestamp issueDate) {
        this.issueDate = issueDate;
    }

    public Timestamp getExpiryDate() {
        return this.expiryDate;
    }

    public void setExpiryDate(Timestamp expiryDate) {
        this.expiryDate = expiryDate;
    }

    @Size(max = 50)
    public String getIssuePlace() {
        return this.issuePlace;
    }

    public void setIssuePlace(String issuePlace) {
        this.issuePlace = issuePlace;
    }

    @Size(max = 50)
    public String getNameOnPassport() {
        return this.nameOnPassport;
    }

    public void setNameOnPassport(String nameOnPassport) {
        this.nameOnPassport = nameOnPassport;
    }

    public Long getIdentificationTypeFk() {
        return this.identificationTypeFk;
    }

    public void setIdentificationTypeFk(Long identificationTypeFk) {
        this.identificationTypeFk = identificationTypeFk;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("NationalityDetail (");

        sb.append(id);
        sb.append(", ").append(nationalityFk);
        sb.append(", ").append(permanentResidenceFk);
        sb.append(", ").append(residentialStatusFk);
        sb.append(", ").append(studentFk);
        sb.append(", ").append(passportNo);
        sb.append(", ").append(issueDate);
        sb.append(", ").append(expiryDate);
        sb.append(", ").append(issuePlace);
        sb.append(", ").append(nameOnPassport);
        sb.append(", ").append(identificationTypeFk);

        sb.append(")");
        return sb.toString();
    }
}
