/*
 * This file is generated by jOOQ.
*/
package schemas.public_.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PersonalDetail implements Serializable {

    private static final long serialVersionUID = -549610878;

    private Long      id;
    private Timestamp dateOfBirth;
    private String    familyName;
    private String    firstName;
    private byte[]    gender;
    private String    middleName;
    private String    preferedName;
    private String    title;

    public PersonalDetail() {}

    public PersonalDetail(PersonalDetail value) {
        this.id = value.id;
        this.dateOfBirth = value.dateOfBirth;
        this.familyName = value.familyName;
        this.firstName = value.firstName;
        this.gender = value.gender;
        this.middleName = value.middleName;
        this.preferedName = value.preferedName;
        this.title = value.title;
    }

    public PersonalDetail(
        Long      id,
        Timestamp dateOfBirth,
        String    familyName,
        String    firstName,
        byte[]    gender,
        String    middleName,
        String    preferedName,
        String    title
    ) {
        this.id = id;
        this.dateOfBirth = dateOfBirth;
        this.familyName = familyName;
        this.firstName = firstName;
        this.gender = gender;
        this.middleName = middleName;
        this.preferedName = preferedName;
        this.title = title;
    }

    @NotNull
    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Timestamp getDateOfBirth() {
        return this.dateOfBirth;
    }

    public void setDateOfBirth(Timestamp dateOfBirth) {
        this.dateOfBirth = dateOfBirth;
    }

    @Size(max = 255)
    public String getFamilyName() {
        return this.familyName;
    }

    public void setFamilyName(String familyName) {
        this.familyName = familyName;
    }

    @Size(max = 255)
    public String getFirstName() {
        return this.firstName;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    public byte[] getGender() {
        return this.gender;
    }

    public void setGender(byte... gender) {
        this.gender = gender;
    }

    @Size(max = 255)
    public String getMiddleName() {
        return this.middleName;
    }

    public void setMiddleName(String middleName) {
        this.middleName = middleName;
    }

    @Size(max = 255)
    public String getPreferedName() {
        return this.preferedName;
    }

    public void setPreferedName(String preferedName) {
        this.preferedName = preferedName;
    }

    @Size(max = 255)
    public String getTitle() {
        return this.title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("PersonalDetail (");

        sb.append(id);
        sb.append(", ").append(dateOfBirth);
        sb.append(", ").append(familyName);
        sb.append(", ").append(firstName);
        sb.append(", ").append("[binary...]");
        sb.append(", ").append(middleName);
        sb.append(", ").append(preferedName);
        sb.append(", ").append(title);

        sb.append(")");
        return sb.toString();
    }
}
