/*
 * This file is generated by jOOQ.
*/
package schemas.public_.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class VisaDetail implements Serializable {

    private static final long serialVersionUID = -1668113426;

    private Long   id;
    private String endDate;
    private String startDate;
    private String visaType;
    private Long   passportFk;

    public VisaDetail() {}

    public VisaDetail(VisaDetail value) {
        this.id = value.id;
        this.endDate = value.endDate;
        this.startDate = value.startDate;
        this.visaType = value.visaType;
        this.passportFk = value.passportFk;
    }

    public VisaDetail(
        Long   id,
        String endDate,
        String startDate,
        String visaType,
        Long   passportFk
    ) {
        this.id = id;
        this.endDate = endDate;
        this.startDate = startDate;
        this.visaType = visaType;
        this.passportFk = passportFk;
    }

    @NotNull
    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    @Size(max = 255)
    public String getEndDate() {
        return this.endDate;
    }

    public void setEndDate(String endDate) {
        this.endDate = endDate;
    }

    @Size(max = 255)
    public String getStartDate() {
        return this.startDate;
    }

    public void setStartDate(String startDate) {
        this.startDate = startDate;
    }

    @Size(max = 255)
    public String getVisaType() {
        return this.visaType;
    }

    public void setVisaType(String visaType) {
        this.visaType = visaType;
    }

    public Long getPassportFk() {
        return this.passportFk;
    }

    public void setPassportFk(Long passportFk) {
        this.passportFk = passportFk;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("VisaDetail (");

        sb.append(id);
        sb.append(", ").append(endDate);
        sb.append(", ").append(startDate);
        sb.append(", ").append(visaType);
        sb.append(", ").append(passportFk);

        sb.append(")");
        return sb.toString();
    }
}
