/*
 * This file is generated by jOOQ.
*/
package schemas.administrator.tables.daos;


import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;

import schemas.administrator.tables.AcademicYear;
import schemas.administrator.tables.records.AcademicYearRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AcademicYearDao extends DAOImpl<AcademicYearRecord, schemas.administrator.tables.pojos.AcademicYear, Long> {

    /**
     * Create a new AcademicYearDao without any configuration
     */
    public AcademicYearDao() {
        super(AcademicYear.ACADEMIC_YEAR, schemas.administrator.tables.pojos.AcademicYear.class);
    }

    /**
     * Create a new AcademicYearDao with an attached configuration
     */
    public AcademicYearDao(Configuration configuration) {
        super(AcademicYear.ACADEMIC_YEAR, schemas.administrator.tables.pojos.AcademicYear.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Long getId(schemas.administrator.tables.pojos.AcademicYear object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<schemas.administrator.tables.pojos.AcademicYear> fetchById(Long... values) {
        return fetch(AcademicYear.ACADEMIC_YEAR.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public schemas.administrator.tables.pojos.AcademicYear fetchOneById(Long value) {
        return fetchOne(AcademicYear.ACADEMIC_YEAR.ID, value);
    }

    /**
     * Fetch records that have <code>start_year IN (values)</code>
     */
    public List<schemas.administrator.tables.pojos.AcademicYear> fetchByStartYear(String... values) {
        return fetch(AcademicYear.ACADEMIC_YEAR.START_YEAR, values);
    }

    /**
     * Fetch records that have <code>end_year IN (values)</code>
     */
    public List<schemas.administrator.tables.pojos.AcademicYear> fetchByEndYear(String... values) {
        return fetch(AcademicYear.ACADEMIC_YEAR.END_YEAR, values);
    }

    /**
     * Fetch records that have <code>start_month IN (values)</code>
     */
    public List<schemas.administrator.tables.pojos.AcademicYear> fetchByStartMonth(String... values) {
        return fetch(AcademicYear.ACADEMIC_YEAR.START_MONTH, values);
    }

    /**
     * Fetch records that have <code>end_month IN (values)</code>
     */
    public List<schemas.administrator.tables.pojos.AcademicYear> fetchByEndMonth(String... values) {
        return fetch(AcademicYear.ACADEMIC_YEAR.END_MONTH, values);
    }

    /**
     * Fetch records that have <code>status IN (values)</code>
     */
    public List<schemas.administrator.tables.pojos.AcademicYear> fetchByStatus(String... values) {
        return fetch(AcademicYear.ACADEMIC_YEAR.STATUS, values);
    }
}
