/*
 * This file is generated by jOOQ.
*/
package schemas.administrator.tables.daos;


import java.sql.Timestamp;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;

import schemas.administrator.tables.Teach;
import schemas.administrator.tables.records.TeachRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TeachDao extends DAOImpl<TeachRecord, schemas.administrator.tables.pojos.Teach, Long> {

    /**
     * Create a new TeachDao without any configuration
     */
    public TeachDao() {
        super(Teach.TEACH, schemas.administrator.tables.pojos.Teach.class);
    }

    /**
     * Create a new TeachDao with an attached configuration
     */
    public TeachDao(Configuration configuration) {
        super(Teach.TEACH, schemas.administrator.tables.pojos.Teach.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Long getId(schemas.administrator.tables.pojos.Teach object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<schemas.administrator.tables.pojos.Teach> fetchById(Long... values) {
        return fetch(Teach.TEACH.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public schemas.administrator.tables.pojos.Teach fetchOneById(Long value) {
        return fetchOne(Teach.TEACH.ID, value);
    }

    /**
     * Fetch records that have <code>instructor_fk IN (values)</code>
     */
    public List<schemas.administrator.tables.pojos.Teach> fetchByInstructorFk(String... values) {
        return fetch(Teach.TEACH.INSTRUCTOR_FK, values);
    }

    /**
     * Fetch records that have <code>class_fk IN (values)</code>
     */
    public List<schemas.administrator.tables.pojos.Teach> fetchByClassFk(String... values) {
        return fetch(Teach.TEACH.CLASS_FK, values);
    }

    /**
     * Fetch records that have <code>start_date IN (values)</code>
     */
    public List<schemas.administrator.tables.pojos.Teach> fetchByStartDate(Timestamp... values) {
        return fetch(Teach.TEACH.START_DATE, values);
    }

    /**
     * Fetch records that have <code>end_date IN (values)</code>
     */
    public List<schemas.administrator.tables.pojos.Teach> fetchByEndDate(Timestamp... values) {
        return fetch(Teach.TEACH.END_DATE, values);
    }

    /**
     * Fetch records that have <code>drop_teach_reason_fk IN (values)</code>
     */
    public List<schemas.administrator.tables.pojos.Teach> fetchByDropTeachReasonFk(Long... values) {
        return fetch(Teach.TEACH.DROP_TEACH_REASON_FK, values);
    }

    /**
     * Fetch records that have <code>teach_outcome_fk IN (values)</code>
     */
    public List<schemas.administrator.tables.pojos.Teach> fetchByTeachOutcomeFk(Long... values) {
        return fetch(Teach.TEACH.TEACH_OUTCOME_FK, values);
    }
}
