/*
 * This file is generated by jOOQ.
*/
package schemas.public_.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;

import schemas.public_.Keys;
import schemas.public_.Public;
import schemas.public_.tables.records.AnnoucementRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Annoucement extends TableImpl<AnnoucementRecord> {

    private static final long serialVersionUID = -825849517;

    /**
     * The reference instance of <code>public.annoucement</code>
     */
    public static final Annoucement ANNOUCEMENT = new Annoucement();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<AnnoucementRecord> getRecordType() {
        return AnnoucementRecord.class;
    }

    /**
     * The column <code>public.annoucement.id</code>.
     */
    public final TableField<AnnoucementRecord, Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.annoucement.message</code>.
     */
    public final TableField<AnnoucementRecord, String> MESSAGE = createField("message", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

    /**
     * The column <code>public.annoucement.title</code>.
     */
    public final TableField<AnnoucementRecord, String> TITLE = createField("title", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

    /**
     * Create a <code>public.annoucement</code> table reference
     */
    public Annoucement() {
        this("annoucement", null);
    }

    /**
     * Create an aliased <code>public.annoucement</code> table reference
     */
    public Annoucement(String alias) {
        this(alias, ANNOUCEMENT);
    }

    private Annoucement(String alias, Table<AnnoucementRecord> aliased) {
        this(alias, aliased, null);
    }

    private Annoucement(String alias, Table<AnnoucementRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<AnnoucementRecord> getPrimaryKey() {
        return Keys.ANNOUCEMENT_PKEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<AnnoucementRecord>> getKeys() {
        return Arrays.<UniqueKey<AnnoucementRecord>>asList(Keys.ANNOUCEMENT_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Annoucement as(String alias) {
        return new Annoucement(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Annoucement rename(String name) {
        return new Annoucement(name, null);
    }
}
