/*
 * This file is generated by jOOQ.
*/
package schemas.public_.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;

import schemas.public_.Keys;
import schemas.public_.Public;
import schemas.public_.tables.records.DwDimensionsRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DwDimensions extends TableImpl<DwDimensionsRecord> {

    private static final long serialVersionUID = 167072413;

    /**
     * The reference instance of <code>public.dw_dimensions</code>
     */
    public static final DwDimensions DW_DIMENSIONS = new DwDimensions();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<DwDimensionsRecord> getRecordType() {
        return DwDimensionsRecord.class;
    }

    /**
     * The column <code>public.dw_dimensions.id</code>.
     */
    public final TableField<DwDimensionsRecord, Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.dw_dimensions.iid</code>.
     */
    public final TableField<DwDimensionsRecord, String> IID = createField("iid", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

    /**
     * The column <code>public.dw_dimensions.champ</code>.
     */
    public final TableField<DwDimensionsRecord, String> CHAMP = createField("champ", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

    /**
     * The column <code>public.dw_dimensions.entite</code>.
     */
    public final TableField<DwDimensionsRecord, String> ENTITE = createField("entite", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

    /**
     * The column <code>public.dw_dimensions.typechamp</code>.
     */
    public final TableField<DwDimensionsRecord, String> TYPECHAMP = createField("typechamp", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

    /**
     * The column <code>public.dw_dimensions.valeur</code>.
     */
    public final TableField<DwDimensionsRecord, String> VALEUR = createField("valeur", org.jooq.impl.SQLDataType.VARCHAR.length(1000), this, "");

    /**
     * Create a <code>public.dw_dimensions</code> table reference
     */
    public DwDimensions() {
        this("dw_dimensions", null);
    }

    /**
     * Create an aliased <code>public.dw_dimensions</code> table reference
     */
    public DwDimensions(String alias) {
        this(alias, DW_DIMENSIONS);
    }

    private DwDimensions(String alias, Table<DwDimensionsRecord> aliased) {
        this(alias, aliased, null);
    }

    private DwDimensions(String alias, Table<DwDimensionsRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<DwDimensionsRecord> getPrimaryKey() {
        return Keys.DW_DIMENSIONS_PKEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<DwDimensionsRecord>> getKeys() {
        return Arrays.<UniqueKey<DwDimensionsRecord>>asList(Keys.DW_DIMENSIONS_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DwDimensions as(String alias) {
        return new DwDimensions(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public DwDimensions rename(String name) {
        return new DwDimensions(name, null);
    }
}
